//! Minimal test using codegen (not procedural macros)
//!
//! This test uses lifeguard-codegen to generate Entity, Model, Column, etc.
//! before compilation, avoiding E0223 errors from procedural macros.
//!
//! The generated code is in tests/generated/user.rs

// Include generated code (generated by lifeguard-codegen)
// Use include! macro to include the generated file
include!("generated/user.rs");

#[cfg(test)]
mod tests {
    use super::*;
    use lifeguard::{FromRow, LifeEntityName, LifeModelTrait};

    #[test]
    fn test_entity_exists() {
        // Verify User (Entity) unit struct exists and implements required traits
        let entity = User;

        // Test LifeEntityName
        assert_eq!(entity.table_name(), "users");
        assert_eq!(User::default().table_name(), "users");

        // Test Default
        let _default_entity = User::default();
    }

    #[test]
    fn test_column_enum_exists() {
        // Verify Column enum exists and implements Iden
        use sea_query::Iden;

        assert_eq!(Column::Id.unquoted(), "id");
        assert_eq!(Column::Name.unquoted(), "name");
        assert_eq!(Column::Email.unquoted(), "email");
    }

    #[test]
    fn test_primary_key_enum_exists() {
        // Verify PrimaryKey enum exists
        let _pk = PrimaryKey::Id;
    }

    #[test]
    fn test_model_struct_exists() {
        // Verify Model struct exists and can be instantiated
        let model = UserModel {
            id: 1,
            email: "test@example.com".to_string(),
            name: Some("Test User".to_string()),
        };

        assert_eq!(model.id, 1);
        assert_eq!(model.email, "test@example.com");
        assert_eq!(model.name, Some("Test User".to_string()));
    }

    #[test]
    fn test_from_row_trait_implemented() {
        // Verify FromRow trait is implemented for UserModel
        fn _verify_from_row<T: FromRow>() {}
        _verify_from_row::<UserModel>();
    }

    #[test]
    fn test_life_model_trait_implemented() {
        // Verify LifeModelTrait is implemented for User (Entity)
        fn _verify_life_model_trait<E: LifeModelTrait>() {}
        _verify_life_model_trait::<User>();

        // Verify the associated type Model is correct
        fn _verify_model_type<E: LifeModelTrait<Model = UserModel>>() {}
        _verify_model_type::<User>();
    }

    #[test]
    fn test_find_method_works() {
        // Verify User::find() returns SelectQuery
        let _query = User::find();
        // Just verify it compiles - actual execution requires an executor
    }

    #[test]
    fn test_entity_table_name_constant() {
        // Verify User::TABLE_NAME constant exists
        assert_eq!(User::TABLE_NAME, "users");
    }
}
