//! Minimal test to isolate E0223 error
//!
//! This test verifies the nested macro expansion pattern:
//! - LifeModel generates Entity with #[derive(DeriveEntity)]
//! - DeriveEntity (nested expansion) generates LifeModelTrait
//! - LifeModel also generates TestMinimalModel (the Model struct)
//!
//! NOTE: FromRow is not applied here - this test only verifies that the
//! nested macro expansion pattern works and E0223 errors are resolved.
//! FromRow would be applied separately in actual usage.

use lifeguard_derive::LifeModel;

#[test]
fn test_minimal() {
    #[derive(LifeModel)]
    #[table_name = "test_minimal"]
    struct TestMinimal {
        #[primary_key]
        id: i32,
        name: String,
    }
    
    // LifeModel generates:
    // - Entity (with #[derive(DeriveEntity)] which generates LifeModelTrait)
    // - TestMinimalModel (the Model struct)
    // - Column enum
    // - PrimaryKey enum
    
    // Step 1: Verify Entity exists
    let _entity = Entity;
    
    // Step 2: Verify Model exists (generated by LifeModel)
    let _model = TestMinimalModel {
        id: 1,
        name: "test".to_string(),
    };
    
    // Step 3: Verify Column enum exists
    let _column = Column::Id;
    
    // Step 4: Verify PrimaryKey enum exists
    let _pk = PrimaryKey::Id;
}
