//! Integration tests for the `DataLoader` batch fetching architecture.
//!
//! Validates that complex object hierarchy queries are evaluated using exactly N+1 avoidance (i.e. executed collectively)
//! and struct arrays natively hydrate the results without N iterations.

use lifeguard::{
    test_helpers::TestDatabase, LifeExecutor, MayPostgresExecutor,
};
use lifeguard_derive::{LifeModel, LifeRecord};
use lifeguard::ActiveModelTrait;
use lifeguard::query::traits::LifeModelTrait; // Ensure LifeModelTrait is in scope for .find()

fn get_db() -> TestDatabase {
    let ctx = crate::context::get_test_context();
    TestDatabase::with_url(&ctx.pg_url)
}

pub mod post_mod {
    use super::*;
    #[derive(LifeModel, LifeRecord, Clone, Debug)]
    #[table_name = "test_dataloader_posts"]
    pub struct Post {
        #[primary_key]
        #[auto_increment]
        pub id: i32,
        pub title: String,
        pub author_id: i32, // FK to Users
    }
}

pub mod user_mod {
    use super::*;
    #[derive(LifeModel, LifeRecord, Clone, Debug)]
    #[table_name = "test_dataloader_users"]
    pub struct User {
        #[primary_key]
        #[auto_increment]
        pub id: i32,
        pub username: String,
        
        // This denotes a loader relationship between `test_dataloader_users` and `test_dataloader_posts`
        #[has_many(entity = "post_mod::Entity", from = "id", to = "author_id")]
        pub rel_posts: Option<Vec<post_mod::PostModel>>,
    }
}

pub use post_mod::*;
pub use user_mod::*;

fn setup_test_schema(executor: &MayPostgresExecutor) -> Result<(), lifeguard::executor::LifeError> {
    executor.execute("DROP TABLE IF EXISTS test_dataloader_posts CASCADE", &[])?;
    executor.execute("DROP TABLE IF EXISTS test_dataloader_users CASCADE", &[])?;
    
    executor.execute(
        r"
        CREATE TABLE test_dataloader_users (
            id SERIAL PRIMARY KEY,
            username TEXT NOT NULL
        )
        ",
        &[],
    )?;
    
    executor.execute(
        r"
        CREATE TABLE test_dataloader_posts (
            id SERIAL PRIMARY KEY,
            title TEXT NOT NULL,
            author_id INTEGER NOT NULL REFERENCES test_dataloader_users(id)
        )
        ",
        &[],
    )?;
    
    Ok(())
}

#[test]
fn test_dataloader_n_plus_one_batch_execution() {
    let mut db = get_db();
    let _client = db.connect().expect("Failed to connect to database");
    let executor = db.executor().expect("Failed to create executor");
    setup_test_schema(&executor).unwrap();

    // Insert 2 Users with mixed graph Posts
    let mut u1 = UserRecord::new();
    u1.set_username("Alice".to_string());
    let u1_model = u1.save(&executor).expect("Failed to insert user A");

    let mut u2 = UserRecord::new();
    u2.set_username("Bob".to_string());
    let u2_model = u2.save(&executor).expect("Failed to insert user B");

    // Alice has 2 posts
    let mut p1 = PostRecord::new();
    p1.set_title("Alice Post 1".to_string());
    p1.set_author_id(u1_model.id);
    p1.save(&executor).expect("Failed to insert post 1");
    
    let mut p2 = PostRecord::new();
    p2.set_title("Alice Post 2".to_string());
    p2.set_author_id(u1_model.id);
    p2.save(&executor).expect("Failed to insert post 2");

    // Bob has 1 post
    let mut p3 = PostRecord::new();
    p3.set_title("Bob Post 1".to_string());
    p3.set_author_id(u2_model.id);
    p3.save(&executor).expect("Failed to insert post 3");

    // **Query Users and actively request batch hydration logic** (N+1 avoidance)
    // NOTE: This triggers precisely 2 SQL queries behind the scenes!
     // Ensure SelectQuery loader methods are imported
    
    // We utilize the static Entity structures auto-generated by our `LifeModel` derive for the type bounds.
    let users = user_mod::Entity::find()
        .load(post_mod::Entity)
        .all(&executor)
        .expect("Failed to execute data batch sequence");

    assert_eq!(users.len(), 2, "Expected exactly 2 root user items fetched.");
    
    let alice = users.iter().find(|u| u.username == "Alice").unwrap();
    let bob = users.iter().find(|u| u.username == "Bob").unwrap();

    // Verify relations are hydrated dynamically via Option structure
    assert!(alice.rel_posts.is_some(), "Alice posts relationship should not be None");
    let alice_posts = alice.rel_posts.as_ref().unwrap();
    assert_eq!(alice_posts.len(), 2, "Alice should have structurally received exactly 2 nested posts inside her model.");
    assert!(alice_posts.iter().any(|p| p.title == "Alice Post 1"));

    assert!(bob.rel_posts.is_some(), "Bob posts relationship should not be None");
    let bob_posts = bob.rel_posts.as_ref().unwrap();
    assert_eq!(bob_posts.len(), 1, "Bob should sequentially contain just 1 related post entity mapped to his batch lookup."); 
    assert_eq!(bob_posts[0].title, "Bob Post 1");
}
