//! End-to-end subprocess test: `lifeguard-migrate infer-schema` (PRD Phase A — CLI e2e).
//!
//! Requires `CARGO_BIN_EXE_lifeguard-migrate` (set by Cargo when building integration tests) and a
//! Postgres URL; skips when either is missing so `cargo test -p lifeguard-migrate` stays usable offline.

use std::process::Command;

fn postgres_url() -> Option<String> {
    std::env::var("TEST_DATABASE_URL")
        .or_else(|_| std::env::var("DATABASE_URL"))
        .or_else(|_| std::env::var("LIFEGUARD_DATABASE_URL"))
        .ok()
        .filter(|s| !s.trim().is_empty())
}

#[test]
fn infer_schema_cli_prints_generated_banner() {
    let Some(url) = postgres_url() else {
        eprintln!(
            "infer_schema_cli_prints_generated_banner: skipped (set TEST_DATABASE_URL, DATABASE_URL, or LIFEGUARD_DATABASE_URL)"
        );
        return;
    };

    let Some(bin) = std::env::var_os("CARGO_BIN_EXE_lifeguard-migrate") else {
        eprintln!("infer_schema_cli_prints_generated_banner: skipped (CARGO_BIN_EXE_lifeguard-migrate not set — run cargo test -p lifeguard-migrate)");
        return;
    };

    let out = Command::new(&bin)
        .args(["infer-schema", "--database-url", &url])
        .output()
        .unwrap_or_else(|e| panic!("spawn lifeguard-migrate infer-schema: {e}"));

    assert!(
        out.status.success(),
        "infer-schema failed: stderr={stderr}",
        stderr = String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("Generated by lifeguard-migrate infer-schema"),
        "expected banner in stdout, got {} bytes",
        stdout.len()
    );
}
