//! Optional live-PostgreSQL smoke for `infer_schema_rust` (PRD §5.7).
//!
//! When `TEST_DATABASE_URL`, `DATABASE_URL`, or `LIFEGUARD_DATABASE_URL` is set, connects and
//! runs introspection on `public`. Without a URL the test returns immediately (passes) so default
//! `cargo test -p lifeguard-migrate` stays offline. CI can set the same env vars used for other DB tests.

use lifeguard::{connect, MayPostgresExecutor};
use lifeguard_migrate::schema_infer::{infer_schema_rust, InferOptions};

fn postgres_url() -> Option<String> {
    std::env::var("TEST_DATABASE_URL")
        .or_else(|_| std::env::var("DATABASE_URL"))
        .or_else(|_| std::env::var("LIFEGUARD_DATABASE_URL"))
        .ok()
        .filter(|s| !s.trim().is_empty())
}

#[test]
fn infer_schema_rust_live_public_smoke() {
    let Some(url) = postgres_url() else {
        eprintln!(
            "infer_schema_rust_live_public_smoke: skipped (set TEST_DATABASE_URL, DATABASE_URL, or LIFEGUARD_DATABASE_URL)"
        );
        return;
    };

    let client = connect(&url).expect("connect to Postgres for infer-schema smoke");
    let executor = MayPostgresExecutor::new(client);
    let out = infer_schema_rust(
        &executor,
        &InferOptions {
            schema: "public".to_string(),
            tables: vec![],
        },
    )
    .expect("infer_schema_rust");

    assert!(
        out.contains("Generated by lifeguard-migrate infer-schema"),
        "expected banner in output, got {} bytes",
        out.len()
    );
}
