{{- if .Values.exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}-exporter
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
    app: {{ include "postgres.fullname" . }}-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgres.fullname" . }}-exporter
  template:
    metadata:
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
        app: {{ include "postgres.fullname" . }}-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    spec:
      containers:
        - name: postgres-exporter
          image: {{ include "postgres.exporterImage" . }}
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9187
          env:
            {{- if .Values.exporter.dataSourceName }}
            - name: DATA_SOURCE_NAME
              value: {{ .Values.exporter.dataSourceName | quote }}
            {{- else if .Values.auth.existingSecret }}
            - name: DATA_SOURCE_URI
              value: {{ printf "%s.%s.svc.cluster.local:%v/%s?sslmode=disable" (include "postgres.serviceName" .) .Release.Namespace .Values.service.port .Values.auth.database | quote }}
            - name: DATA_SOURCE_USER
              value: {{ .Values.auth.username | quote }}
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgres.secretName" . }}
                  key: {{ .Values.auth.passwordKey }}
            {{- else }}
            - name: DATA_SOURCE_NAME
              value: {{ include "postgres.dataSourceName" . | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- with .Values.exporter.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-exporter
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
    app: {{ include "postgres.fullname" . }}-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
      protocol: TCP
  selector:
    app: {{ include "postgres.fullname" . }}-exporter
{{- end }}
