{{- if .Values.initScripts.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.initConfigMapName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  11-lifeguard-schema.sql: |
{{ .Files.Get "files/11-lifeguard-schema.sql" | indent 4 }}
{{- range .Values.initScripts.extraFiles }}
  {{ . }}: |
{{ $.Files.Get (printf "files/%s" .) | indent 4 }}
{{- end }}
{{- end }}
