{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
    app: {{ include "postgres.primaryName" . }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.password | quote }}
  {{ .Values.auth.replicationPasswordKey }}: {{ .Values.auth.replicationPassword | quote }}
{{- end }}
