//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "appointments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pet_id: Option<i32>,
    pub date: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pets::Entity",
        from = "Column::PetId",
        to = "super::pets::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pets,
}

impl Related<super::pets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
