//! `DataLoader` architecture for resolving N+1 queries.
use crate::executor::LifeExecutor;
use crate::executor::LifeError;
use crate::model::ModelTrait;
use crate::query::traits::{FromRow, LifeModelTrait};
use crate::query::value_conversion::with_converted_params;
use crate::relation::identity::Identity;
use sea_query::{Condition, Expr, ExprTrait, PostgresQueryBuilder};
use std::collections::{HashMap, HashSet};

/// Trait to inject loaded relationships back into the parent model's nested fields.
/// This is typically auto-generated by the `lifeguard-derive` macro for any fields annotated
/// with `#[has_many]`, `#[belongs_to]`, or `#[has_one]`.
pub trait RelationInjector<R: LifeModelTrait> {
    /// Injects a batch of loaded child matching this specific parent into the struct.
    fn inject(&mut self, items: Vec<R::Model>);
}

/// A generic executor box that encapsulates a type-safe batch query resolution
pub trait LoaderExecutor<E: LifeModelTrait> {
    /// Executes the batch query, resolving missing N+1 relationships, and
    /// injecting them into the provided batch array of parent models.
    fn execute(&self, models: &mut [E::Model], exec: &dyn LifeExecutor) -> Result<(), LifeError>;
}

/// Generic Relation Loader for batch-fetching N+1 data arrays map back onto models
pub struct RelationLoader<E, R>
where
    E: LifeModelTrait + crate::Related<R> + 'static,
    R: LifeModelTrait + 'static,
    E::Model: RelationInjector<R> + ModelTrait,
    R::Model: crate::query::traits::FromRow + ModelTrait + Clone,
{
    _e: std::marker::PhantomData<E>,
    _r: std::marker::PhantomData<R>,
}

impl<E, R> Default for RelationLoader<E, R>
where
    E: LifeModelTrait + crate::Related<R> + 'static,
    R: LifeModelTrait + 'static,
    E::Model: RelationInjector<R> + ModelTrait,
    R::Model: crate::query::traits::FromRow + ModelTrait + Clone,
{
    fn default() -> Self {
        Self::new()
    }
}

impl<E, R> RelationLoader<E, R>
where
    E: LifeModelTrait + crate::Related<R> + 'static,
    R: LifeModelTrait + 'static,
    E::Model: RelationInjector<R> + ModelTrait,
    R::Model: crate::query::traits::FromRow + ModelTrait + Clone,
{
    #[must_use]
    pub fn new() -> Self {
        Self {
            _e: std::marker::PhantomData,
            _r: std::marker::PhantomData,
        }
    }
}

/// `true` if the value is suitable for a non-null foreign-key side in batch loading.
///
/// Lists every `Variant(None)` for the `sea-query` features enabled on this crate. If lifeguard
/// enables additional `sea-query` features (e.g. `with-uuid`, `postgres-array`), extend this
/// match so `None` inner values are not treated as present.
fn relation_side_value_present(v: &sea_query::Value) -> bool {
    match v {
        sea_query::Value::Bool(None)
        | sea_query::Value::TinyInt(None)
        | sea_query::Value::SmallInt(None)
        | sea_query::Value::Int(None)
        | sea_query::Value::BigInt(None)
        | sea_query::Value::TinyUnsigned(None)
        | sea_query::Value::SmallUnsigned(None)
        | sea_query::Value::Unsigned(None)
        | sea_query::Value::BigUnsigned(None)
        | sea_query::Value::Float(None)
        | sea_query::Value::Double(None)
        | sea_query::Value::String(None)
        | sea_query::Value::Char(None)
        | sea_query::Value::Bytes(None) => false,
        sea_query::Value::Json(None) => false,
        sea_query::Value::ChronoDate(None)
        | sea_query::Value::ChronoTime(None)
        | sea_query::Value::ChronoDateTime(None)
        | sea_query::Value::ChronoDateTimeUtc(None)
        | sea_query::Value::ChronoDateTimeLocal(None)
        | sea_query::Value::ChronoDateTimeWithTimeZone(None) => false,
        _ => true,
    }
}

fn identity_column_names(id: &Identity) -> Result<Vec<String>, LifeError> {
    let n = id.arity();
    if n == 0 {
        return Err(LifeError::Other(
            "Relation identity has no columns (DataLoader)".to_string(),
        ));
    }
    Ok(id.iter().map(ToString::to_string).collect())
}

fn fk_tuple_map_key(values: &[sea_query::Value]) -> String {
    values
        .iter()
        .map(|v| format!("{v:?}"))
        .collect::<Vec<_>>()
        .join("\x1f")
}

/// Read one composite key from `model` using `cols` in order; `None` if any part missing or null.
fn extract_fk_tuple(model: &impl ModelTrait, cols: &[String]) -> Option<Vec<sea_query::Value>> {
    let mut out = Vec::with_capacity(cols.len());
    for c in cols {
        let v = model.get_by_column_name(c)?;
        if !relation_side_value_present(&v) {
            return None;
        }
        out.push(v);
    }
    Some(out)
}

impl<E, R> LoaderExecutor<E> for RelationLoader<E, R>
where
    E: LifeModelTrait + crate::Related<R> + 'static,
    R: LifeModelTrait + 'static,
    E::Model: RelationInjector<R> + ModelTrait,
    R::Model: crate::query::traits::FromRow + ModelTrait + Clone,
{
    fn execute(&self, models: &mut [E::Model], exec: &dyn LifeExecutor) -> Result<(), LifeError> {
        if models.is_empty() {
            return Ok(());
        }

        let rel_def = E::to();
        let from_cols = identity_column_names(&rel_def.from_col)?;
        let to_cols = identity_column_names(&rel_def.to_col)?;
        if from_cols.len() != to_cols.len() {
            return Err(LifeError::Other(format!(
                "Relation from_col arity {} does not match to_col arity {} (DataLoader)",
                from_cols.len(),
                to_cols.len()
            )));
        }
        let arity = from_cols.len();

        let mut unique_tuples: Vec<Vec<sea_query::Value>> = Vec::new();
        let mut seen_keys: HashSet<String> = HashSet::new();

        for model in models.iter() {
            if let Some(t) = extract_fk_tuple(model, &from_cols) {
                let k = fk_tuple_map_key(&t);
                if seen_keys.insert(k) {
                    unique_tuples.push(t);
                }
            }
        }

        if unique_tuples.is_empty() {
            for model in models.iter_mut() {
                model.inject(Vec::new());
            }
            return Ok(());
        }

        let mut query = R::find();

        if arity == 1 {
            let col = &to_cols[0];
            let flat: Vec<sea_query::Value> = unique_tuples.iter().map(|t| t[0].clone()).collect();
            query = query.filter(Expr::col(sea_query::Alias::new(col)).is_in(flat));
        } else {
            let mut or_cond = Condition::any();
            for tup in &unique_tuples {
                let mut and_cond = Condition::all();
                for (col_name, val) in to_cols.iter().zip(tup.iter()) {
                    and_cond = and_cond.add(Expr::col(sea_query::Alias::new(col_name)).eq(val.clone()));
                }
                or_cond = or_cond.add(and_cond);
            }
            query = query.filter(or_cond);
        }

        let loaders = std::mem::take(&mut query.loaders);
        let (sql, values) = query.apply_soft_delete().build(PostgresQueryBuilder);
        let children: Vec<R::Model> = with_converted_params(&values, |params| {
            let rows = exec.query_all(&sql, params)?;
            let mut results = Vec::new();
            for row in rows {
                let model = <R::Model as FromRow>::from_row(&row).map_err(|e| {
                    LifeError::ParseError(format!("Failed to parse row: {e}"))
                })?;
                results.push(model);
            }
            for loader in &loaders {
                loader.execute(&mut results, exec)?;
            }
            Ok(results)
        })?;

        let mut grouped_children: HashMap<String, Vec<R::Model>> = HashMap::new();
        for child in children {
            if let Some(t) = extract_fk_tuple(&child, &to_cols) {
                let key = fk_tuple_map_key(&t);
                grouped_children.entry(key).or_default().push(child);
            }
        }

        for model in models.iter_mut() {
            if let Some(t) = extract_fk_tuple(model, &from_cols) {
                let key = fk_tuple_map_key(&t);
                if let Some(group) = grouped_children.get(&key) {
                    model.inject(group.clone());
                } else {
                    model.inject(Vec::new());
                }
            } else {
                model.inject(Vec::new());
            }
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn relation_side_value_present_filters_null_variants() {
        assert!(!relation_side_value_present(&sea_query::Value::Int(None)));
        assert!(!relation_side_value_present(&sea_query::Value::String(None)));
        assert!(!relation_side_value_present(&sea_query::Value::BigInt(None)));
        assert!(!relation_side_value_present(&sea_query::Value::Float(None)));
        assert!(!relation_side_value_present(&sea_query::Value::Double(None)));
        assert!(!relation_side_value_present(&sea_query::Value::Bool(None)));
        assert!(!relation_side_value_present(&sea_query::Value::Json(None)));
        assert!(!relation_side_value_present(&sea_query::Value::ChronoDateTimeUtc(None)));
        assert!(relation_side_value_present(&sea_query::Value::Int(Some(1))));
        assert!(relation_side_value_present(&sea_query::Value::String(Some("x".into()))));
    }

    #[test]
    fn fk_tuple_map_key_distinct() {
        let a = vec![sea_query::Value::Int(Some(1)), sea_query::Value::Int(Some(2))];
        let b = vec![sea_query::Value::Int(Some(1)), sea_query::Value::Int(Some(3))];
        assert_ne!(fk_tuple_map_key(&a), fk_tuple_map_key(&b));
    }
}
