//! `DataLoader` architecture for resolving N+1 queries.
use crate::executor::LifeExecutor;
use crate::query::traits::LifeModelTrait;
use crate::executor::LifeError;
use crate::model::ModelTrait;
use sea_query::{Expr, ExprTrait};
use std::collections::HashMap;

/// Trait to inject loaded relationships back into the parent model's nested fields.
/// This is typically auto-generated by the `lifeguard-derive` macro for any fields annotated 
/// with `#[has_many]`, `#[belongs_to]`, or `#[has_one]`.
pub trait RelationInjector<R: LifeModelTrait> {
    /// Injects a batch of loaded child matching this specific parent into the struct. 
    fn inject(&mut self, items: Vec<R::Model>);
}

/// A generic executor box that encapsulates a type-safe batch query resolution
pub trait LoaderExecutor<E: LifeModelTrait> {
    /// Executes the batch query, resolving missing N+1 relationships, and
    /// injecting them into the provided batch array of parent models.
    fn execute(&self, models: &mut [E::Model], exec: &dyn LifeExecutor) -> Result<(), LifeError>;
}

/// Generic Relation Loader for batch-fetching N+1 data arrays map back onto models
pub struct RelationLoader<E, R>
where
    E: LifeModelTrait + crate::Related<R> + 'static,
    R: LifeModelTrait + 'static,
    E::Model: RelationInjector<R> + ModelTrait,
    R::Model: crate::query::traits::FromRow + ModelTrait,
{
    _e: std::marker::PhantomData<E>,
    _r: std::marker::PhantomData<R>,
}

impl<E, R> Default for RelationLoader<E, R>
where
    E: LifeModelTrait + crate::Related<R> + 'static,
    R: LifeModelTrait + 'static,
    E::Model: RelationInjector<R> + ModelTrait,
    R::Model: crate::query::traits::FromRow + ModelTrait,
 {
    fn default() -> Self {
        Self::new()
    }
}

impl<E, R> RelationLoader<E, R>
where
    E: LifeModelTrait + crate::Related<R> + 'static,
    R: LifeModelTrait + 'static,
    E::Model: RelationInjector<R> + ModelTrait,
    R::Model: crate::query::traits::FromRow + ModelTrait,
{
    #[must_use] pub fn new() -> Self {
        Self {
            _e: std::marker::PhantomData,
            _r: std::marker::PhantomData,
        }
    }
}

impl<E, R> LoaderExecutor<E> for RelationLoader<E, R>
where
    E: LifeModelTrait + crate::Related<R> + 'static,
    R: LifeModelTrait + 'static,
    E::Model: RelationInjector<R> + ModelTrait,
    R::Model: crate::query::traits::FromRow + ModelTrait,
{
    fn execute(&self, models: &mut [E::Model], exec: &dyn LifeExecutor) -> Result<(), LifeError> {
        if models.is_empty() {
            return Ok(());
        }

        let rel_def = E::to();
        
        // Ensure Identity is supported (Unary only for POC)
        // Extract the string names
        use crate::relation::identity::Identity;
        let from_col_name = match &rel_def.from_col {
            Identity::Unary(iden) => iden.to_string(),
            _ => return Err(LifeError::Other("Composite keys not yet supported for DataLoader batch fetching".to_string())),
        };
        let to_col_name = match &rel_def.to_col {
            Identity::Unary(iden) => iden.to_string(),
            _ => return Err(LifeError::Other("Composite keys not yet supported for DataLoader batch fetching".to_string())),
        };

        let mut parent_ids: Vec<sea_query::Value> = Vec::new();
        
        // 1. Extract Parent IDs by utilizing LifeModelTrait primary key access
        for model in models.iter() {
            if let Some(val) = model.get_by_column_name(&from_col_name) {
                // Avoid pushing None values (e.g. NULL foreign keys)
                if !matches!(val, sea_query::Value::String(None) | sea_query::Value::Int(None)) { 
                    parent_ids.push(val);
                }
            }
        }

        if parent_ids.is_empty() {
            return Ok(());
        }

        // 2. Fetch all child elements matching ANY of the parent IDs (The IN clause)
        // We know R is the child LifeModelTrait. So R::find() gives a SelectQuery<R>.
        // We evaluate using the `alias` to map the dynamic to_col string since Column enum may be opaque.
        let children: Vec<R::Model> = R::find()
            .filter(Expr::col(sea_query::Alias::new(&to_col_name)).is_in(parent_ids))
            .all(&exec)?;
        
        // 3. Group children structurally via format stringification to avoid sea_query::Value missing Hash
        //
        // NOTE ON STRINGIFICATION vs HASHING:
        // The fundamental problem stringification seamlessly solves is navigating SeaQuery’s explicit lack 
        // of Hash on floating types like f32/f64. Standard Rust explicitly forbids implementing Hash and 
        // Eq on floats (since NaN != NaN mathematically), meaning sea_query::Value cannot natively act as 
        // a dictionary key in maps. Instead of jumping through complex hoops trying to dynamically enforce 
        // that foreign relationships cannot map to table columns utilizing floats (or writing unsafe 
        // byte-mapping structs), utilizing stringified formats effortlessly unifies everything, including 
        // numeric boundaries and timestamps natively inside a dictionary for our child hydration step.
        // It is an incredibly pragmatic trade-off.
        //
        // TODO(performance): If data loader maps grow to 10k+ rows and string allocation becomes a bottleneck, 
        // consider migrating to a structural checking enum or byte-slice hashing algorithm that intentionally 
        // panics on float keys.
        let mut grouped_children: HashMap<String, Vec<R::Model>> = HashMap::new();
        for child in children {
            if let Some(child_fk_val) = child.get_by_column_name(&to_col_name) {
                let key = format!("{child_fk_val:?}");
                grouped_children.entry(key).or_default().push(child);
            }
        }

        // 4. Inject grouped relationships back onto the original model array
        for model in models.iter_mut() {
            if let Some(parent_fk_val) = model.get_by_column_name(&from_col_name) {
                let key = format!("{parent_fk_val:?}");
                if let Some(group) = grouped_children.remove(&key) {
                    model.inject(group);
                } else {
                    model.inject(Vec::new());
                }
            } else {
                model.inject(Vec::new());
            }
        }
        
        Ok(())
    }
}
