//! Core traits for entity and model definitions.
//!
//! This module provides the fundamental traits that entities must implement:
//! - `LifeEntityName`: Provides table name information
//! - `LifeModelTrait`: Main entity trait with CRUD operations
//!
//! Generic methods take `executor: &E` where `E: LifeExecutor`. If you hold a trait object as
//! `let ex: &dyn LifeExecutor`, pass **`&ex`** (so `E` is `&dyn LifeExecutor`, which implements
//! [`LifeExecutor`](crate::executor::LifeExecutor) via a blanket impl), not `ex` alone.
//!
//! # Examples
//!
//! ```no_run
//! use lifeguard::{LifeEntityName, LifeExecutor, LifeModelTrait};
//!
//! # #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
//! # enum UserColumn {
//! #     Id,
//! # }
//! # impl sea_query::Iden for UserColumn {
//! #     fn unquoted(&self) -> &'static str {
//! #         match self {
//! #             UserColumn::Id => "id",
//! #         }
//! #     }
//! # }
//! # impl sea_query::IdenStatic for UserColumn {
//! #     fn as_str(&self) -> &'static str {
//! #         match self {
//! #             UserColumn::Id => "id",
//! #         }
//! #     }
//! # }
//! # lifeguard::impl_column_def_helper_for_test!(UserColumn);
//! # #[derive(Clone, Debug)]
//! # struct UserModel {
//! #     id: i32,
//! #     name: String,
//! # }
//! # impl lifeguard::FromRow for UserModel {
//! #     fn from_row(_row: &may_postgres::Row) -> Result<Self, may_postgres::Error> {
//! #         todo!()
//! #     }
//! # }
//! # impl lifeguard::ModelTrait for UserModel {
//! #     type Entity = User;
//! #     fn get(&self, col: UserColumn) -> sea_query::Value {
//! #         match col {
//! #             UserColumn::Id => sea_query::Value::Int(Some(self.id)),
//! #         }
//! #     }
//! #     fn set(
//! #         &mut self,
//! #         _: UserColumn,
//! #         _: sea_query::Value,
//! #     ) -> Result<(), lifeguard::ModelError> {
//! #         Ok(())
//! #     }
//! #     fn get_primary_key_value(&self) -> sea_query::Value {
//! #         sea_query::Value::Int(Some(self.id))
//! #     }
//! #     fn get_primary_key_identity(&self) -> lifeguard::relation::identity::Identity {
//! #         lifeguard::relation::identity::Identity::Unary("id".into())
//! #     }
//! # }
//! # struct User;
//! # impl lifeguard::LifeEntityName for User {
//! #     fn table_name(&self) -> &'static str {
//! #         "users"
//! #     }
//! # }
//! # impl Default for User {
//! #     fn default() -> Self {
//! #         User
//! #     }
//! # }
//! # impl lifeguard::LifeModelTrait for User {
//! #     type Model = UserModel;
//! #     type Column = UserColumn;
//! # }
//! # fn main() -> Result<(), Box<dyn std::error::Error>> {
//! # let executor: &dyn LifeExecutor = todo!();
//!
//! let _users = User::find().all(&executor)?;
//! # Ok(())
//! # }
//! ```

use crate::executor::LifeExecutor;

use crate::query::select::SelectQuery;

/// Trait for providing table name information.
///
///
/// Similar to `SeaORM`'s `EntityName`, this trait provides the table name
/// and requires `Default` so entities can be instantiated for query building.
pub trait LifeEntityName: Default {
    /// Get the name of the table.
    fn table_name(&self) -> &'static str;

    /// Get the schema name (if any).
    /// Returns `None` if no schema is specified (default schema).
    fn schema_name(&self) -> Option<&'static str> {
        None
    }
}

/// Trait for `LifeModel` entities that provides CRUD operations.
///
///
/// This trait is similar to `SeaORM`'s `EntityTrait` and provides methods for
/// querying and manipulating database records. The trait is implemented by
/// the `LifeModel` derive macro for the Entity (struct name), not the Model.
///
pub trait LifeModelTrait: LifeEntityName {
    /// The Model type that represents database rows.
    ///
    /// Note: The `FromRow` bound is not enforced here to avoid macro expansion issues.
    /// The bound is checked at usage sites (in `SelectQuery` methods) where it can be verified.
    type Model;

    /// The Column enum type for this entity.
    ///
    /// This is generated by the `LifeModel` derive macro and provides type-safe column access.
    type Column: sea_query::IdenStatic + crate::query::column::column_trait::ColumnDefHelper;

    /// Returns the soft delete column if this entity supports soft deletion
    #[must_use]
    fn soft_delete_column() -> Option<Self::Column> {
        None
    }

    /// Get all column variants for this entity.
    ///
    /// Returns a static slice of all `Column` enum variants.
    /// This is useful for iterating through all columns, e.g., when building `SELECT` queries
    /// that need to check for `select_as` expressions.
    ///
    /// # Default Implementation
    ///
    /// Returns an empty slice. The `LifeModel` macro generates implementations
    /// that return all column variants via the `Column::all_columns()` method.
    ///
    /// # Example
    ///
    /// ```no_run
    /// use lifeguard::LifeModelTrait;
    ///
    /// # #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    /// # enum UserColumn {
    /// #     Id,
    /// # }
    /// # impl sea_query::Iden for UserColumn {
    /// #     fn unquoted(&self) -> &'static str {
    /// #         match self {
    /// #             UserColumn::Id => "id",
    /// #         }
    /// #     }
    /// # }
    /// # impl sea_query::IdenStatic for UserColumn {
    /// #     fn as_str(&self) -> &'static str {
    /// #         match self {
    /// #             UserColumn::Id => "id",
    /// #         }
    /// #     }
    /// # }
    /// # lifeguard::impl_column_def_helper_for_test!(UserColumn);
    /// # struct User;
    /// # impl lifeguard::LifeEntityName for User {
    /// #     fn table_name(&self) -> &'static str {
    /// #         "users"
    /// #     }
    /// # }
    /// # impl Default for User {
    /// #     fn default() -> Self {
    /// #         User
    /// #     }
    /// # }
    /// # impl lifeguard::LifeModelTrait for User {
    /// #     type Model = ();
    /// #     type Column = UserColumn;
    /// # }
    /// let columns = User::all_columns();
    /// for column in columns {
    ///     let _ = column;
    /// }
    /// ```
    #[must_use]
    fn all_columns() -> &'static [Self::Column]
    where
        Self: Sized,
    {
        // Default implementation returns empty slice
        // Macro will override this with actual implementation
        &[]
    }

    /// Primary key column for stable [`crate::query::CursorPaginator`] ordering when the cursor
    /// sort column is not unique.
    ///
    /// **Opt-in:** set `#[cursor_tiebreak = "PkColumnVariant"]` on the `LifeModel` struct (single-column
    /// PK only). Returns `None` if omitted, for composite PKs, or for manual `LifeModelTrait` impls
    /// without that attribute.
    #[must_use]
    fn cursor_tiebreak_column() -> Option<Self::Column>
    where
        Self::Column: Copy,
        Self: Sized,
    {
        None
    }

    /// Start a query builder for finding records.
    ///
    ///
    /// This method is defined in the trait (not generated by macro) to avoid
    /// trait bound resolution issues during macro expansion. The macro only
    /// generates the trait implementation with associated types.
    ///
    /// # Returns
    ///
    /// Returns a query builder that can be chained with filters, ordering, pagination, etc.
    ///
    /// # Example
    ///
    /// ```no_run
    /// use lifeguard::{LifeEntityName, LifeExecutor, LifeModelTrait};
    ///
    /// # #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    /// # enum UserColumn {
    /// #     Id,
    /// # }
    /// # impl sea_query::Iden for UserColumn {
    /// #     fn unquoted(&self) -> &'static str {
    /// #         match self {
    /// #             UserColumn::Id => "id",
    /// #         }
    /// #     }
    /// # }
    /// # impl sea_query::IdenStatic for UserColumn {
    /// #     fn as_str(&self) -> &'static str {
    /// #         match self {
    /// #             UserColumn::Id => "id",
    /// #         }
    /// #     }
    /// # }
    /// # lifeguard::impl_column_def_helper_for_test!(UserColumn);
    /// # struct User; // Entity
    /// # #[derive(Clone, Debug)]
    /// # struct UserModel {
    /// #     id: i32,
    /// # }
    /// # impl lifeguard::FromRow for UserModel {
    /// #     fn from_row(_row: &may_postgres::Row) -> Result<Self, may_postgres::Error> {
    /// #         todo!()
    /// #     }
    /// # }
    /// # impl lifeguard::ModelTrait for UserModel {
    /// #     type Entity = User;
    /// #     fn get(&self, col: UserColumn) -> sea_query::Value {
    /// #         match col {
    /// #             UserColumn::Id => sea_query::Value::Int(Some(self.id)),
    /// #         }
    /// #     }
    /// #     fn set(
    /// #         &mut self,
    /// #         _: UserColumn,
    /// #         _: sea_query::Value,
    /// #     ) -> Result<(), lifeguard::ModelError> {
    /// #         Ok(())
    /// #     }
    /// #     fn get_primary_key_value(&self) -> sea_query::Value {
    /// #         sea_query::Value::Int(Some(self.id))
    /// #     }
    /// #     fn get_primary_key_identity(&self) -> lifeguard::relation::identity::Identity {
    /// #         lifeguard::relation::identity::Identity::Unary("id".into())
    /// #     }
    /// # }
    /// # impl lifeguard::LifeEntityName for User {
    /// #     fn table_name(&self) -> &'static str {
    /// #         "users"
    /// #     }
    /// # }
    /// # impl Default for User {
    /// #     fn default() -> Self {
    /// #         User
    /// #     }
    /// # }
    /// # impl lifeguard::LifeModelTrait for User {
    /// #     type Model = UserModel;
    /// #     type Column = UserColumn;
    /// # }
    /// # fn main() -> Result<(), Box<dyn std::error::Error>> {
    /// # let executor: &dyn LifeExecutor = todo!();
    ///
    /// let _users = User::find().all(&executor)?;
    /// # Ok(())
    /// # }
    /// ```
    #[must_use]
    fn find() -> SelectQuery<Self>
    where
        Self: Sized,
    {
        SelectQuery::new()
    }

    /// Insert an `ActiveModel` (`Record`) into the database.
    ///
    ///
    /// This is a convenience method that delegates to `ActiveModelTrait::insert()`.
    /// It provides a static method on `Entity` for consistency with `SeaORM`'s API.
    ///
    /// # Arguments
    ///
    /// * `active_model` - The `ActiveModel` (`Record`) to insert
    /// * `executor` - The database executor to use
    ///
    /// # Returns
    ///
    /// Returns the inserted model on success, or an error if the operation fails.
    ///
    /// # Example
    ///
    /// ```no_run
    /// use lifeguard::{ActiveModelTrait, LifeExecutor, LifeModelTrait};
    ///
    /// # #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    /// # enum UserColumn {
    /// #     Id,
    /// # }
    /// # impl sea_query::Iden for UserColumn {
    /// #     fn unquoted(&self) -> &'static str {
    /// #         match self {
    /// #             UserColumn::Id => "id",
    /// #         }
    /// #     }
    /// # }
    /// # impl sea_query::IdenStatic for UserColumn {
    /// #     fn as_str(&self) -> &'static str {
    /// #         match self {
    /// #             UserColumn::Id => "id",
    /// #         }
    /// #     }
    /// # }
    /// # lifeguard::impl_column_def_helper_for_test!(UserColumn);
    /// # struct User; // Entity
    /// # #[derive(Clone, Debug)]
    /// # struct UserModel {
    /// #     id: i32,
    /// #     name: String,
    /// # }
    /// # impl lifeguard::ModelTrait for UserModel {
    /// #     type Entity = User;
    /// #     fn get(&self, col: UserColumn) -> sea_query::Value {
    /// #         match col {
    /// #             UserColumn::Id => sea_query::Value::Int(Some(self.id)),
    /// #         }
    /// #     }
    /// #     fn set(
    /// #         &mut self,
    /// #         _: UserColumn,
    /// #         _: sea_query::Value,
    /// #     ) -> Result<(), lifeguard::ModelError> {
    /// #         Ok(())
    /// #     }
    /// #     fn get_primary_key_value(&self) -> sea_query::Value {
    /// #         sea_query::Value::Int(Some(self.id))
    /// #     }
    /// #     fn get_primary_key_identity(&self) -> lifeguard::relation::identity::Identity {
    /// #         lifeguard::relation::identity::Identity::Unary("id".into())
    /// #     }
    /// # }
    /// # #[derive(Clone, Debug)]
    /// # struct UserRecord;
    /// # impl lifeguard::ActiveModelTrait for UserRecord {
    /// #     type Entity = User;
    /// #     type Model = UserModel;
    /// #     fn get(&self, _: UserColumn) -> Option<sea_query::Value> {
    /// #         None
    /// #     }
    /// #     fn set(
    /// #         &mut self,
    /// #         _: UserColumn,
    /// #         _: sea_query::Value,
    /// #     ) -> Result<(), lifeguard::ActiveModelError> {
    /// #         Ok(())
    /// #     }
    /// #     fn take(&mut self, _: UserColumn) -> Option<sea_query::Value> {
    /// #         None
    /// #     }
    /// #     fn reset(&mut self) {}
    /// # }
    /// # impl lifeguard::LifeEntityName for User {
    /// #     fn table_name(&self) -> &'static str {
    /// #         "users"
    /// #     }
    /// # }
    /// # impl Default for User {
    /// #     fn default() -> Self {
    /// #         User
    /// #     }
    /// # }
    /// # impl lifeguard::LifeModelTrait for User {
    /// #     type Model = UserModel;
    /// #     type Column = UserColumn;
    /// # }
    /// # fn main() -> Result<(), Box<dyn std::error::Error>> {
    /// # let executor: &dyn LifeExecutor = todo!();
    /// # let record = UserRecord;
    ///
    /// let _model = User::insert(record, &executor)?;
    /// # Ok(())
    /// # }
    /// ```
    ///
    /// # Errors
    ///
    /// Returns `ActiveModelError` if the insert operation fails.
    fn insert<AM, E>(
        active_model: AM,
        executor: &E,
    ) -> Result<Self::Model, crate::active_model::ActiveModelError>
    where
        Self: Sized,
        AM: crate::active_model::ActiveModelTrait<Model = Self::Model>,
        E: LifeExecutor,
    {
        active_model.insert(executor)
    }

    /// Update an `ActiveModel` (`Record`) in the database.
    ///
    ///
    /// This is a convenience method that delegates to `ActiveModelTrait::update()`.
    /// It provides a static method on `Entity` for consistency with `SeaORM`'s API.
    ///
    /// # Arguments
    ///
    /// * `active_model` - The `ActiveModel` (`Record`) to update
    /// * `executor` - The database executor to use
    ///
    /// # Returns
    ///
    /// Returns the updated model on success, or an error if the operation fails.
    ///
    /// # Note
    ///
    /// This requires a primary key to be set in the `ActiveModel`.
    ///
    /// # Example
    ///
    /// ```no_run
    /// use lifeguard::{ActiveModelTrait, LifeExecutor, LifeModelTrait};
    ///
    /// # #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    /// # enum UserColumn {
    /// #     Id,
    /// # }
    /// # impl sea_query::Iden for UserColumn {
    /// #     fn unquoted(&self) -> &'static str {
    /// #         match self {
    /// #             UserColumn::Id => "id",
    /// #         }
    /// #     }
    /// # }
    /// # impl sea_query::IdenStatic for UserColumn {
    /// #     fn as_str(&self) -> &'static str {
    /// #         match self {
    /// #             UserColumn::Id => "id",
    /// #         }
    /// #     }
    /// # }
    /// # lifeguard::impl_column_def_helper_for_test!(UserColumn);
    /// # struct User; // Entity
    /// # #[derive(Clone, Debug)]
    /// # struct UserModel {
    /// #     id: i32,
    /// #     name: String,
    /// # }
    /// # impl lifeguard::ModelTrait for UserModel {
    /// #     type Entity = User;
    /// #     fn get(&self, col: UserColumn) -> sea_query::Value {
    /// #         match col {
    /// #             UserColumn::Id => sea_query::Value::Int(Some(self.id)),
    /// #         }
    /// #     }
    /// #     fn set(
    /// #         &mut self,
    /// #         _: UserColumn,
    /// #         _: sea_query::Value,
    /// #     ) -> Result<(), lifeguard::ModelError> {
    /// #         Ok(())
    /// #     }
    /// #     fn get_primary_key_value(&self) -> sea_query::Value {
    /// #         sea_query::Value::Int(Some(self.id))
    /// #     }
    /// #     fn get_primary_key_identity(&self) -> lifeguard::relation::identity::Identity {
    /// #         lifeguard::relation::identity::Identity::Unary("id".into())
    /// #     }
    /// # }
    /// # #[derive(Clone, Debug)]
    /// # struct UserRecord;
    /// # impl lifeguard::ActiveModelTrait for UserRecord {
    /// #     type Entity = User;
    /// #     type Model = UserModel;
    /// #     fn get(&self, _: UserColumn) -> Option<sea_query::Value> {
    /// #         None
    /// #     }
    /// #     fn set(
    /// #         &mut self,
    /// #         _: UserColumn,
    /// #         _: sea_query::Value,
    /// #     ) -> Result<(), lifeguard::ActiveModelError> {
    /// #         Ok(())
    /// #     }
    /// #     fn take(&mut self, _: UserColumn) -> Option<sea_query::Value> {
    /// #         None
    /// #     }
    /// #     fn reset(&mut self) {}
    /// # }
    /// # impl lifeguard::LifeEntityName for User {
    /// #     fn table_name(&self) -> &'static str {
    /// #         "users"
    /// #     }
    /// # }
    /// # impl Default for User {
    /// #     fn default() -> Self {
    /// #         User
    /// #     }
    /// # }
    /// # impl lifeguard::LifeModelTrait for User {
    /// #     type Model = UserModel;
    /// #     type Column = UserColumn;
    /// # }
    /// # fn main() -> Result<(), Box<dyn std::error::Error>> {
    /// # let executor: &dyn LifeExecutor = todo!();
    /// # let record = UserRecord;
    ///
    /// let _model = User::update(record, &executor)?;
    /// # Ok(())
    /// # }
    /// ```
    ///
    /// # Errors
    ///
    /// Returns `ActiveModelError` if the update operation fails.
    fn update<AM, E>(
        active_model: AM,
        executor: &E,
    ) -> Result<Self::Model, crate::active_model::ActiveModelError>
    where
        Self: Sized,
        AM: crate::active_model::ActiveModelTrait<Model = Self::Model>,
        E: LifeExecutor,
    {
        active_model.update(executor)
    }

    /// Delete a record from the database by primary key.
    ///
    ///
    /// This is a convenience method that delegates to `ActiveModelTrait::delete()`.
    /// It provides a static method on Entity for consistency with `SeaORM`'s API.
    ///
    /// # Arguments
    ///
    /// * `active_model` - The `ActiveModel` (`Record`) with primary key set
    /// * `executor` - The database executor to use
    ///
    /// # Returns
    ///
    /// Returns `Ok(())` on success, or an error if the operation fails.
    ///
    /// # Note
    ///
    /// This requires a primary key to be set in the `ActiveModel`.
    ///
    /// # Example
    ///
    /// ```no_run
    /// use lifeguard::{ActiveModelTrait, LifeExecutor, LifeModelTrait};
    ///
    /// # #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    /// # enum UserColumn {
    /// #     Id,
    /// # }
    /// # impl sea_query::Iden for UserColumn {
    /// #     fn unquoted(&self) -> &'static str {
    /// #         match self {
    /// #             UserColumn::Id => "id",
    /// #         }
    /// #     }
    /// # }
    /// # impl sea_query::IdenStatic for UserColumn {
    /// #     fn as_str(&self) -> &'static str {
    /// #         match self {
    /// #             UserColumn::Id => "id",
    /// #         }
    /// #     }
    /// # }
    /// # lifeguard::impl_column_def_helper_for_test!(UserColumn);
    /// # struct User; // Entity
    /// # #[derive(Clone, Debug)]
    /// # struct UserModel {
    /// #     id: i32,
    /// #     name: String,
    /// # }
    /// # impl lifeguard::ModelTrait for UserModel {
    /// #     type Entity = User;
    /// #     fn get(&self, col: UserColumn) -> sea_query::Value {
    /// #         match col {
    /// #             UserColumn::Id => sea_query::Value::Int(Some(self.id)),
    /// #         }
    /// #     }
    /// #     fn set(
    /// #         &mut self,
    /// #         _: UserColumn,
    /// #         _: sea_query::Value,
    /// #     ) -> Result<(), lifeguard::ModelError> {
    /// #         Ok(())
    /// #     }
    /// #     fn get_primary_key_value(&self) -> sea_query::Value {
    /// #         sea_query::Value::Int(Some(self.id))
    /// #     }
    /// #     fn get_primary_key_identity(&self) -> lifeguard::relation::identity::Identity {
    /// #         lifeguard::relation::identity::Identity::Unary("id".into())
    /// #     }
    /// # }
    /// # #[derive(Clone, Debug)]
    /// # struct UserRecord;
    /// # impl lifeguard::ActiveModelTrait for UserRecord {
    /// #     type Entity = User;
    /// #     type Model = UserModel;
    /// #     fn get(&self, _: UserColumn) -> Option<sea_query::Value> {
    /// #         None
    /// #     }
    /// #     fn set(
    /// #         &mut self,
    /// #         _: UserColumn,
    /// #         _: sea_query::Value,
    /// #     ) -> Result<(), lifeguard::ActiveModelError> {
    /// #         Ok(())
    /// #     }
    /// #     fn take(&mut self, _: UserColumn) -> Option<sea_query::Value> {
    /// #         None
    /// #     }
    /// #     fn reset(&mut self) {}
    /// # }
    /// # impl lifeguard::LifeEntityName for User {
    /// #     fn table_name(&self) -> &'static str {
    /// #         "users"
    /// #     }
    /// # }
    /// # impl Default for User {
    /// #     fn default() -> Self {
    /// #         User
    /// #     }
    /// # }
    /// # impl lifeguard::LifeModelTrait for User {
    /// #     type Model = UserModel;
    /// #     type Column = UserColumn;
    /// # }
    /// # fn main() -> Result<(), Box<dyn std::error::Error>> {
    /// # let executor: &dyn LifeExecutor = todo!();
    /// # let record = UserRecord;
    ///
    /// User::delete(record, &executor)?;
    /// # Ok(())
    /// # }
    /// ```
    ///
    /// # Errors
    ///
    /// Returns `ActiveModelError` if the delete operation fails.
    fn delete<AM, E>(
        active_model: AM,
        executor: &E,
    ) -> Result<(), crate::active_model::ActiveModelError>
    where
        Self: Sized,
        AM: crate::active_model::ActiveModelTrait<Model = Self::Model>,
        E: LifeExecutor,
    {
        active_model.delete(executor)
    }
}

/// Builds a [`may_postgres::Error`] when a column decodes from SQL but fails a Rust-side range check
/// (for example, a negative `BIGINT` cannot become `u64` via [`TryFrom`]).
///
/// `may_postgres::Error` has no first-class API for unsigned range failures; this uses a
/// [`may_postgres::Row::try_get`] path that fails for typical integral columns (Rust type mismatch),
/// with a fallback for unusual wire types (OOB column index) so the function always returns `Err`.
pub fn from_row_unsigned_try_from_failed(
    row: &may_postgres::Row,
    column_name: &str,
) -> may_postgres::Error {
    match row.try_get::<&str, &[u8]>(column_name) {
        Err(e) => e,
        Ok(_) => {
            // BYTEA-compatible value on a column the model treats as integral: OOB index always errors.
            #[allow(clippy::expect_used)]
            {
                row.try_get::<usize, i32>(row.len())
                    .expect_err("out-of-bounds column index must fail")
            }
        }
    }
}

/// Trait for types that can be created from a database row
pub trait FromRow: Sized {
    /// Convert a database row to this type
    ///
    /// # Arguments
    ///
    /// * `row` - The `may_postgres::Row` to convert from
    ///
    /// # Errors
    ///
    /// Returns `may_postgres::Error` if the conversion fails.
    fn from_row(row: &may_postgres::Row) -> Result<Self, may_postgres::Error>;
}

// FromRow implementation for serde_json::Value
use serde_json::Value as JsonValue;
impl FromRow for JsonValue {
    fn from_row(row: &may_postgres::Row) -> Result<Self, may_postgres::Error> {
        if row.is_empty() {
            // No columns: force a column-bounds error (same family as invalid index on empty).
            return row.try_get::<_, i32>(0).map(|_| JsonValue::Null);
        }
        let text: String = row.try_get(0)?;
        match serde_json::from_str(&text) {
            Ok(json) => Ok(json),
            Err(e) => Err(may_postgres::Error::user_column_decode_failed(
                0,
                e.to_string(),
            )),
        }
    }
}
