//! Registry loader for accessing compiled entity registry
//!
//! This module provides functionality to load and use the entity registry
//! that was generated by the build script. The registry contains compiled
//! entities that can be used for SQL generation.

use std::path::{Path, PathBuf};
use std::fs;
use std::env;

/// Attempt to load the entity registry from the user's project
///
/// This function looks for the registry in common locations:
/// 1. OUT_DIR environment variable (if running from build context)
/// 2. target/debug/build/<package>/out/entity_registry.rs
/// 3. target/release/build/<package>/out/entity_registry.rs
///
/// Returns the path to the registry file if found, or None if not found.
pub fn find_registry_path() -> Option<PathBuf> {
    // Try OUT_DIR first (if we're in a build context)
    if let Ok(out_dir) = env::var("OUT_DIR") {
        let registry_path = Path::new(&out_dir).join("entity_registry.rs");
        if registry_path.exists() {
            return Some(registry_path);
        }
    }
    
    // Try to find it in target directory
    // Look for target/debug/build or target/release/build
    let current_dir = env::current_dir().ok()?;
    let target_dirs = [
        current_dir.join("target/debug/build"),
        current_dir.join("target/release/build"),
    ];
    
    for target_dir in &target_dirs {
        if !target_dir.exists() {
            continue;
        }
        
        // Look in all build directories
        if let Ok(entries) = fs::read_dir(target_dir) {
            for entry in entries.flatten() {
                let build_dir = entry.path();
                if build_dir.is_dir() {
                    let registry_path = build_dir.join("out/entity_registry.rs");
                    if registry_path.exists() {
                        return Some(registry_path);
                    }
                }
            }
        }
    }
    
    None
}

/// Check if entity registry is available
pub fn is_registry_available() -> bool {
    find_registry_path().is_some()
}

/// Get instructions for setting up the registry
pub fn get_setup_instructions() -> String {
    r#"Entity registry not found. To use compiled entities for migrations:

1. Add a build.rs file to your project root (see examples/build.rs.example)

2. Add to your Cargo.toml:
   [package]
   build = "build.rs"
   
   [build-dependencies]
   lifeguard-migrate = { path = "path/to/lifeguard-migrate", version = "0.1.0" }

3. Include the registry in your lib.rs or main.rs:
   #[path = concat!(env!("OUT_DIR"), "/entity_registry.rs")]
   mod entity_registry;

4. Build your project: cargo build

The registry will be generated automatically during compilation.
"#.to_string()
}
