//! PostgreSQL → Rust `LifeModel` / `LifeRecord` sketch generation (PRD Phase A).
//!
//! Introspects `information_schema` and emits conservative Rust types. Unknown types are
//! omitted with a comment line (SI-2). Secondary **btree** indexes (non-primary `pg_index` rows)
//! are read from catalog and emitted as `#[index = "..."]` when expression coverage can be inferred.

use lifeguard::{
    index_definition_to_derive_index_value, index_key_parts_coverage_columns, IndexBtreeNulls,
    IndexBtreeSort, IndexDefinition, IndexKeyPart, LifeError, LifeExecutor,
};
use may_postgres::Row;
use regex::Regex;
use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

/// Options for [`infer_schema_rust`].
#[derive(Debug, Clone)]
pub struct InferOptions {
    /// PostgreSQL schema name (e.g. `public`).
    pub schema: String,
    /// If non-empty, only these tables (unqualified names, matched case-sensitively as in PG).
    pub tables: Vec<String>,
}

impl Default for InferOptions {
    fn default() -> Self {
        Self {
            schema: "public".to_string(),
            tables: Vec::new(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct ColumnMeta {
    pub table_name: String,
    pub column_name: String,
    pub ordinal: i32,
    pub data_type: String,
    pub udt_name: String,
    pub is_nullable: bool,
}

/// Introspect schema and return Rust source (module-style, stdout-friendly).
pub fn infer_schema_rust(
    executor: &dyn LifeExecutor,
    options: &InferOptions,
) -> Result<String, LifeError> {
    let columns = fetch_columns(executor, &options.schema)?;
    let pks = fetch_primary_keys(executor, &options.schema)?;
    let table_columns = table_column_sets_for_infer(&columns, options);
    let indexes = fetch_btree_indexes(executor, &options.schema, options, &table_columns)?;
    Ok(emit_inferred_rust(options, columns, pks, &indexes))
}

fn table_column_sets_for_infer(
    columns: &[ColumnMeta],
    options: &InferOptions,
) -> HashMap<String, HashSet<String>> {
    let mut m: HashMap<String, HashSet<String>> = HashMap::new();
    for c in columns {
        if !options.tables.is_empty() && !options.tables.iter().any(|t| t == &c.table_name) {
            continue;
        }
        m.entry(c.table_name.clone())
            .or_default()
            .insert(c.column_name.clone());
    }
    m
}

/// Build Rust source from introspection results (used by [`infer_schema_rust`] and golden tests).
pub(crate) fn emit_inferred_rust(
    options: &InferOptions,
    columns: Vec<ColumnMeta>,
    pks: HashMap<String, Vec<String>>,
    indexes_by_table: &HashMap<String, Vec<IndexDefinition>>,
) -> String {
    let mut by_table: HashMap<String, Vec<ColumnMeta>> = HashMap::new();
    for c in columns {
        if !options.tables.is_empty() && !options.tables.iter().any(|t| t == &c.table_name) {
            continue;
        }
        by_table.entry(c.table_name.clone()).or_default().push(c);
    }

    for cols in by_table.values_mut() {
        cols.sort_by_key(|c| c.ordinal);
    }

    let mut table_names: Vec<String> = by_table.keys().cloned().collect();
    table_names.sort();

    let mut need_chrono = false;
    let mut need_uuid = false;
    let mut need_json = false;
    let mut need_decimal = false;
    for c in by_table.values().flatten() {
        if let Some((_, _)) = map_pg_to_rust(&c.data_type, &c.udt_name, c.is_nullable) {
            let dt = c.data_type.as_str();
            let udt = c.udt_name.as_str();
            if matches!(
                dt,
                "timestamp without time zone" | "timestamp with time zone" | "date"
            ) || matches!(udt, "timestamptz" | "timestamp")
            {
                need_chrono = true;
            }
            if dt == "uuid" || udt == "uuid" {
                need_uuid = true;
            }
            if matches!(dt, "json" | "jsonb") || matches!(udt, "json" | "jsonb") {
                need_json = true;
            }
            if matches!(dt, "numeric" | "decimal") || udt == "numeric" {
                need_decimal = true;
            }
        }
    }

    let mut out = String::new();
    writeln!(
        out,
        "// Generated by lifeguard-migrate infer-schema — review types and primary keys.\n\
         // PRD: docs/planning/PRD_SCHEMA_VALIDATORS_SESSION_AND_SCOPES.md\n"
    )
    .unwrap();
    writeln!(out, "use lifeguard_derive::{{LifeModel, LifeRecord}};").unwrap();
    if need_chrono {
        writeln!(
            out,
            "use chrono::{{DateTime, NaiveDate, NaiveDateTime, Utc}};"
        )
        .unwrap();
    }
    if need_uuid {
        writeln!(out, "use uuid::Uuid;").unwrap();
    }
    if need_json {
        writeln!(out, "use serde_json::Value;").unwrap();
    }
    if need_decimal {
        writeln!(out, "use rust_decimal::Decimal;").unwrap();
    }

    for table in table_names {
        let Some(mut cols) = by_table.remove(&table) else {
            continue;
        };
        let pk_cols: Vec<String> = pks.get(&table).cloned().unwrap_or_default();
        let pk_set: HashSet<String> = pk_cols.iter().cloned().collect();

        let struct_name = table_to_struct_name(&table);
        writeln!(out).unwrap();
        writeln!(out, "/// Table `{}`.`{}`", options.schema, table).unwrap();
        writeln!(
            out,
            "#[derive(Debug, Clone, PartialEq, LifeModel, LifeRecord)]"
        )
        .unwrap();
        writeln!(out, "#[table_name = \"{}\"]", table).unwrap();
        if let Some(idxs) = indexes_by_table.get(&table) {
            for idx in idxs {
                let mut v = String::new();
                if idx.unique {
                    v.push_str("UNIQUE ");
                }
                v.push_str(&index_definition_to_derive_index_value(idx));
                let esc = v.replace('\\', "\\\\").replace('"', "\\\"");
                writeln!(out, "#[index = \"{esc}\"]").unwrap();
            }
        }
        writeln!(out, "pub struct {} {{", struct_name).unwrap();

        for col in &cols {
            let rust_type = map_pg_to_rust(&col.data_type, &col.udt_name, col.is_nullable);
            if let Some((ty, attrs)) = rust_type {
                let field = sanitize_field_ident(&col.column_name);
                for line in attrs {
                    writeln!(out, "    {}", line).unwrap();
                }
                if pk_set.contains(&col.column_name) {
                    writeln!(out, "    #[primary_key]").unwrap();
                }
                writeln!(out, "    pub {}: {},", field, ty).unwrap();
            } else {
                writeln!(
                    out,
                    "    // OMITTED: {} — unsupported type data_type={} udt_name={}",
                    col.column_name, col.data_type, col.udt_name
                )
                .unwrap();
            }
        }

        writeln!(out, "}}").unwrap();
    }

    out
}

fn catalog_nulls_to_option(ord_desc: bool, nulls_first: bool) -> Option<IndexBtreeNulls> {
    if ord_desc {
        if nulls_first {
            None
        } else {
            Some(IndexBtreeNulls::Last)
        }
    } else if nulls_first {
        Some(IndexBtreeNulls::First)
    } else {
        None
    }
}

fn infer_expr_coverage_tokens(sql: &str, table_cols: &HashSet<String>) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    for ch in sql.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            cur.push(ch);
        } else {
            if !cur.is_empty() && table_cols.contains(&cur) && !out.contains(&cur) {
                out.push(cur.clone());
            }
            cur.clear();
        }
    }
    if !cur.is_empty() && table_cols.contains(&cur) && !out.contains(&cur) {
        out.push(cur);
    }
    out
}

fn parse_indexdef_include_where(def: &str) -> (Vec<String>, Option<String>) {
    let re = Regex::new(r"(?i)\bINCLUDE\s*\(([^)]*)\)").expect("INCLUDE regex");
    let include = re
        .captures(def)
        .and_then(|c| c.get(1))
        .map(|m| {
            m.as_str()
                .split(',')
                .map(|s| s.trim().to_string())
                .filter(|s| !s.is_empty())
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    let lower = def.to_ascii_lowercase();
    let where_clause = lower.rfind(" where ").map(|p| {
        def[p + 7..]
            .trim()
            .trim_end_matches(|c: char| c == ';' || c.is_whitespace())
            .to_string()
    });
    (include, where_clause)
}

fn fetch_pg_indexdef_map(
    executor: &dyn LifeExecutor,
    schema: &str,
) -> Result<HashMap<(String, String), String>, LifeError> {
    let sql = "SELECT tablename, indexname, indexdef FROM pg_indexes WHERE schemaname = $1";
    let rows = executor.query_all(sql, &[&schema])?;
    let mut map = HashMap::new();
    for row in rows {
        let table: String = row
            .try_get(0)
            .map_err(|e| LifeError::Other(format!("infer pg_indexes table: {e}")))?;
        let index: String = row
            .try_get(1)
            .map_err(|e| LifeError::Other(format!("infer pg_indexes index: {e}")))?;
        let def: String = row
            .try_get(2)
            .map_err(|e| LifeError::Other(format!("infer pg_indexes def: {e}")))?;
        map.insert((table, index), def);
    }
    Ok(map)
}

fn build_index_key_part_from_catalog_row(
    attnum: i32,
    ord_desc: bool,
    nulls_first: bool,
    collname: Option<String>,
    opcname: Option<String>,
    attname: Option<String>,
    keydef: String,
    table_cols: &HashSet<String>,
) -> IndexKeyPart {
    let sort = if ord_desc {
        Some(IndexBtreeSort::Desc)
    } else {
        None
    };
    let nulls = catalog_nulls_to_option(ord_desc, nulls_first);
    let collate = collname.filter(|n| !n.is_empty());
    let opcn = opcname.filter(|n| !n.is_empty());
    if attnum == 0 || attname.as_ref().map_or(true, |a| a.is_empty()) {
        let coverage_columns = infer_expr_coverage_tokens(&keydef, table_cols);
        return IndexKeyPart::Expression {
            sql: keydef.trim().to_string(),
            coverage_columns,
            opclass: opcn,
            collate,
            sort,
            nulls,
        };
    }
    IndexKeyPart::Column {
        name: attname.unwrap_or_default(),
        opclass: opcn,
        collate,
        sort,
        nulls,
    }
}

fn fetch_btree_indexes(
    executor: &dyn LifeExecutor,
    schema: &str,
    options: &InferOptions,
    table_cols: &HashMap<String, HashSet<String>>,
) -> Result<HashMap<String, Vec<IndexDefinition>>, LifeError> {
    let indexdef_map = fetch_pg_indexdef_map(executor, schema)?;
    let sql = r#"
        SELECT
            t.relname::text AS table_name,
            ic.relname::text AS index_name,
            ix.indisunique,
            u.key_ord::int AS key_ord,
            u.attnum::int AS attnum,
            (((
                (ix.indoption::int2[])[array_lower(ix.indkey::int2[], 1) + u.key_ord - 1]
            )::int) & 1) <> 0 AS ord_desc,
            (((
                (ix.indoption::int2[])[array_lower(ix.indkey::int2[], 1) + u.key_ord - 1]
            )::int) & 2) <> 0 AS nulls_first,
            coll.collname::text AS collname,
            opc.opcname::text AS opcname,
            a.attname::text AS attname,
            pg_get_indexdef(ic.oid, u.key_ord::int, true) AS keydef
        FROM pg_index ix
        JOIN pg_class ic ON ic.oid = ix.indexrelid
        JOIN pg_class t ON t.oid = ix.indrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace AND n.nspname = $1
        JOIN pg_am am ON am.oid = ic.relam AND am.amname = 'btree'
        CROSS JOIN LATERAL (
            SELECT
                slot.attnum::int AS attnum,
                row_number() OVER ()::int AS key_ord
            FROM unnest(ix.indkey::int2[]) AS slot(attnum)
        ) u
        LEFT JOIN pg_collation coll ON coll.oid = NULLIF(
            (ix.indcollation::oid[])[array_lower(ix.indkey::int2[], 1) + u.key_ord - 1],
            0::oid
        )
        LEFT JOIN pg_attribute a ON a.attrelid = ix.indrelid
            AND a.attnum = u.attnum
            AND u.attnum <> 0
        LEFT JOIN pg_opclass opc ON opc.oid = (ix.indclass::oid[])[
            array_lower(ix.indkey::int2[], 1) + u.key_ord - 1
        ]
        WHERE NOT ix.indisprimary
          AND ix.indisvalid
          AND t.relkind = 'r'
        ORDER BY t.relname, ic.relname, u.key_ord
    "#;
    let rows = executor.query_all(sql, &[&schema]).map_err(|e| {
        LifeError::Other(format!(
            "infer-schema: btree index catalog query failed (requires PostgreSQL pg_index): {e}"
        ))
    })?;
    #[derive(Default)]
    struct Acc {
        unique: bool,
        parts: Vec<(i32, IndexKeyPart)>,
    }
    let mut grouped: HashMap<(String, String), Acc> = HashMap::new();
    for row in rows {
        let table_name: String = row
            .try_get(0)
            .map_err(|e| LifeError::Other(format!("infer index table: {e}")))?;
        if !options.tables.is_empty() && !options.tables.iter().any(|t| t == &table_name) {
            continue;
        }
        let index_name: String = row
            .try_get(1)
            .map_err(|e| LifeError::Other(format!("infer index name: {e}")))?;
        let indisunique: bool = row
            .try_get(2)
            .map_err(|e| LifeError::Other(format!("infer index unique: {e}")))?;
        let key_ord: i32 = row
            .try_get(3)
            .map_err(|e| LifeError::Other(format!("infer index ord: {e}")))?;
        let attnum: i32 = row
            .try_get(4)
            .map_err(|e| LifeError::Other(format!("infer index attnum: {e}")))?;
        let ord_desc: bool = row
            .try_get(5)
            .map_err(|e| LifeError::Other(format!("infer index ord_desc: {e}")))?;
        let nulls_first: bool = row
            .try_get(6)
            .map_err(|e| LifeError::Other(format!("infer index nulls_first: {e}")))?;
        let collname: Option<String> = row.try_get(7).ok();
        let opcname: Option<String> = row.try_get(8).ok();
        let attname: Option<String> = row.try_get(9).ok();
        let keydef: String = row
            .try_get(10)
            .map_err(|e| LifeError::Other(format!("infer index keydef: {e}")))?;
        let cols_hint = table_cols.get(&table_name).cloned().unwrap_or_default();
        let part = build_index_key_part_from_catalog_row(
            attnum,
            ord_desc,
            nulls_first,
            collname,
            opcname,
            attname,
            keydef,
            &cols_hint,
        );
        let e = grouped
            .entry((table_name, index_name))
            .or_insert_with(|| Acc {
                unique: indisunique,
                parts: Vec::new(),
            });
        e.parts.push((key_ord, part));
    }
    for acc in grouped.values_mut() {
        acc.parts.sort_by_key(|(o, _)| *o);
    }
    let mut out: HashMap<String, Vec<IndexDefinition>> = HashMap::new();
    for ((table_name, index_name), mut acc) in grouped {
        let parts: Vec<IndexKeyPart> = acc.parts.drain(..).map(|(_, p)| p).collect();
        if parts.iter().any(|p| {
            matches!(
                p,
                IndexKeyPart::Expression {
                    coverage_columns,
                    ..
                } if coverage_columns.is_empty()
            )
        }) {
            continue;
        }
        let columns = index_key_parts_coverage_columns(&parts);
        let (include_columns, partial_where) = indexdef_map
            .get(&(table_name.clone(), index_name.clone()))
            .map(|d| parse_indexdef_include_where(d))
            .unwrap_or((Vec::new(), None));
        let def = IndexDefinition {
            name: index_name,
            columns,
            key_list_sql: None,
            key_parts: parts,
            include_columns,
            unique: acc.unique,
            partial_where,
        };
        out.entry(table_name).or_default().push(def);
    }
    for v in out.values_mut() {
        v.sort_by(|a, b| a.name.cmp(&b.name));
    }
    Ok(out)
}

fn fetch_columns(executor: &dyn LifeExecutor, schema: &str) -> Result<Vec<ColumnMeta>, LifeError> {
    let sql = r"
        SELECT table_name, column_name, ordinal_position, data_type, udt_name, is_nullable
        FROM information_schema.columns
        WHERE table_schema = $1
        ORDER BY table_name, ordinal_position
    ";
    let rows = executor.query_all(sql, &[&schema])?;
    let mut out = Vec::with_capacity(rows.len());
    for row in rows {
        out.push(parse_column_row(row)?);
    }
    Ok(out)
}

fn parse_column_row(row: Row) -> Result<ColumnMeta, LifeError> {
    let table_name: String = row
        .try_get(0)
        .map_err(|e| LifeError::Other(format!("infer schema column table_name: {e}")))?;
    let column_name: String = row
        .try_get(1)
        .map_err(|e| LifeError::Other(format!("infer schema column_name: {e}")))?;
    let ordinal: i32 = row
        .try_get(2)
        .map_err(|e| LifeError::Other(format!("infer schema ordinal: {e}")))?;
    let data_type: String = row
        .try_get(3)
        .map_err(|e| LifeError::Other(format!("infer schema data_type: {e}")))?;
    let udt_name: String = row
        .try_get(4)
        .map_err(|e| LifeError::Other(format!("infer schema udt_name: {e}")))?;
    let is_nullable: String = row
        .try_get(5)
        .map_err(|e| LifeError::Other(format!("infer schema is_nullable: {e}")))?;
    let is_nullable = is_nullable.eq_ignore_ascii_case("YES");
    Ok(ColumnMeta {
        table_name,
        column_name,
        ordinal,
        data_type,
        udt_name,
        is_nullable,
    })
}

fn fetch_primary_keys(
    executor: &dyn LifeExecutor,
    schema: &str,
) -> Result<HashMap<String, Vec<String>>, LifeError> {
    let sql = r"
        SELECT tc.table_name, kcu.column_name, kcu.ordinal_position
        FROM information_schema.table_constraints AS tc
        JOIN information_schema.key_column_usage AS kcu
          ON tc.constraint_catalog = kcu.constraint_catalog
         AND tc.constraint_schema = kcu.constraint_schema
         AND tc.constraint_name = kcu.constraint_name
        WHERE tc.table_schema = $1
          AND tc.constraint_type = 'PRIMARY KEY'
        ORDER BY tc.table_name, kcu.ordinal_position
    ";
    let rows = executor.query_all(sql, &[&schema])?;
    let mut map: HashMap<String, Vec<String>> = HashMap::new();
    for row in rows {
        let table: String = row
            .try_get(0)
            .map_err(|e| LifeError::Other(format!("infer pk table_name: {e}")))?;
        let col: String = row
            .try_get(1)
            .map_err(|e| LifeError::Other(format!("infer pk column_name: {e}")))?;
        map.entry(table).or_default().push(col);
    }
    Ok(map)
}

/// Returns `(type_str, extra_attr_lines)` or `None` if unsupported.
fn map_pg_to_rust(
    data_type: &str,
    udt_name: &str,
    nullable: bool,
) -> Option<(String, Vec<String>)> {
    let base = match data_type {
        "integer" | "int4" => "i32".to_string(),
        "bigint" | "int8" => "i64".to_string(),
        "smallint" | "int2" => "i16".to_string(),
        "boolean" | "bool" => "bool".to_string(),
        "text" | "character varying" | "varchar" | "character" | "char" | "name" => {
            "String".to_string()
        }
        "timestamp without time zone" => "chrono::NaiveDateTime".to_string(),
        "timestamp with time zone" => "chrono::DateTime<chrono::Utc>".to_string(),
        "date" => "chrono::NaiveDate".to_string(),
        "uuid" => "uuid::Uuid".to_string(),
        "json" | "jsonb" => "serde_json::Value".to_string(),
        "numeric" | "decimal" => "rust_decimal::Decimal".to_string(),
        "double precision" => "f64".to_string(),
        "real" | "float4" => "f32".to_string(),
        "bytea" => "Vec<u8>".to_string(),
        _ => match udt_name {
            "int4" => "i32".to_string(),
            "int8" => "i64".to_string(),
            "int2" => "i16".to_string(),
            "bool" => "bool".to_string(),
            "text" | "varchar" => "String".to_string(),
            "uuid" => "uuid::Uuid".to_string(),
            "json" | "jsonb" => "serde_json::Value".to_string(),
            "numeric" => "rust_decimal::Decimal".to_string(),
            "timestamptz" => "chrono::DateTime<chrono::Utc>".to_string(),
            "timestamp" => "chrono::NaiveDateTime".to_string(),
            _ => return None,
        },
    };

    let ty = if nullable {
        format!("Option<{base}>")
    } else {
        base
    };
    Some((ty, Vec::new()))
}

fn table_to_struct_name(table: &str) -> String {
    table
        .split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().chain(c).collect(),
            }
        })
        .collect()
}

fn sanitize_field_ident(name: &str) -> String {
    match name {
        "type" | "mod" | "fn" | "let" | "struct" | "enum" | "use" | "crate" | "self" | "super"
        | "where" | "ref" | "mut" | "move" | "async" | "await" | "loop" | "match" => {
            format!("r#{name}")
        }
        _ => name.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn golden_path(name: &str) -> String {
        format!("{}/tests/golden/{name}", env!("CARGO_MANIFEST_DIR"))
    }

    /// When **`LIFEGUARD_BLESS_INFER_SCHEMA_GOLDENS=1`**, overwrites the golden file with `got`
    /// (maintainer workflow after intentional emitter changes). Otherwise asserts equality.
    fn assert_infer_schema_golden(rel_path: &str, got: &str) {
        let path = golden_path(rel_path);
        if std::env::var("LIFEGUARD_BLESS_INFER_SCHEMA_GOLDENS")
            .map(|v| v == "1")
            .unwrap_or(false)
        {
            std::fs::write(&path, got).unwrap_or_else(|e| panic!("bless write {path}: {e}"));
            return;
        }
        let expected =
            std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
        assert_eq!(got, expected);
    }

    #[test]
    fn golden_emit_single_table_widgets() {
        let columns = vec![
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "name".into(),
                ordinal: 2,
                data_type: "text".into(),
                udt_name: "text".into(),
                is_nullable: true,
            },
        ];
        let mut pks = HashMap::new();
        pks.insert("widgets".into(), vec!["id".into()]);
        let got = emit_inferred_rust(&InferOptions::default(), columns, pks, &HashMap::new());
        assert_infer_schema_golden("infer_widgets.expected.rs", &got);
    }

    #[test]
    fn golden_emit_omitted_unsupported_column() {
        let columns = vec![
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "meta".into(),
                ordinal: 2,
                data_type: "unknown_pg".into(),
                udt_name: "custom".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "name".into(),
                ordinal: 3,
                data_type: "text".into(),
                udt_name: "text".into(),
                is_nullable: true,
            },
        ];
        let mut pks = HashMap::new();
        pks.insert("widgets".into(), vec!["id".into()]);
        let got = emit_inferred_rust(&InferOptions::default(), columns, pks, &HashMap::new());
        assert_infer_schema_golden("infer_omitted_column.expected.rs", &got);
    }

    #[test]
    fn golden_emit_composite_primary_key() {
        let columns = vec![
            ColumnMeta {
                table_name: "pair_keys".into(),
                column_name: "site_id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "pair_keys".into(),
                column_name: "item_id".into(),
                ordinal: 2,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
        ];
        let mut pks = HashMap::new();
        pks.insert("pair_keys".into(), vec!["site_id".into(), "item_id".into()]);
        let got = emit_inferred_rust(&InferOptions::default(), columns, pks, &HashMap::new());
        assert_infer_schema_golden("infer_composite_pk.expected.rs", &got);
    }

    #[test]
    fn golden_table_filter_includes_only_named_tables() {
        let columns = vec![
            ColumnMeta {
                table_name: "aaa_other".into(),
                column_name: "id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "name".into(),
                ordinal: 2,
                data_type: "text".into(),
                udt_name: "text".into(),
                is_nullable: true,
            },
        ];
        let mut pks = HashMap::new();
        pks.insert("aaa_other".into(), vec!["id".into()]);
        pks.insert("widgets".into(), vec!["id".into()]);
        let opts = InferOptions {
            schema: "public".into(),
            tables: vec!["widgets".into()],
        };
        let got = emit_inferred_rust(&opts, columns, pks, &HashMap::new());
        assert_infer_schema_golden("infer_widgets.expected.rs", &got);
    }

    #[test]
    fn golden_sql_keyword_column_becomes_raw_identifier() {
        let columns = vec![
            ColumnMeta {
                table_name: "kind_rows".into(),
                column_name: "id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "kind_rows".into(),
                column_name: "type".into(),
                ordinal: 2,
                data_type: "text".into(),
                udt_name: "text".into(),
                is_nullable: false,
            },
        ];
        let mut pks = HashMap::new();
        pks.insert("kind_rows".into(), vec!["id".into()]);
        let got = emit_inferred_rust(&InferOptions::default(), columns, pks, &HashMap::new());
        assert_infer_schema_golden("infer_sql_keyword_field.expected.rs", &got);
    }

    #[test]
    fn emit_inferred_rust_emits_index_attributes() {
        let columns = vec![
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "email".into(),
                ordinal: 2,
                data_type: "text".into(),
                udt_name: "text".into(),
                is_nullable: true,
            },
        ];
        let mut pks = HashMap::new();
        pks.insert("widgets".into(), vec!["id".into()]);
        let idx = IndexDefinition {
            name: "idx_widgets_lower_email".into(),
            columns: vec!["email".into()],
            key_list_sql: None,
            key_parts: vec![IndexKeyPart::Expression {
                sql: "lower(email)".into(),
                coverage_columns: vec!["email".into()],
                opclass: None,
                collate: None,
                sort: None,
                nulls: None,
            }],
            include_columns: vec![],
            unique: false,
            partial_where: None,
        };
        let mut idx_map = HashMap::new();
        idx_map.insert("widgets".into(), vec![idx]);
        let got = emit_inferred_rust(&InferOptions::default(), columns, pks, &idx_map);
        assert!(
            got.contains("#[index = \"idx_widgets_lower_email(lower(email) | email)\"]"),
            "got:\n{got}"
        );
    }

    #[test]
    fn table_to_struct_name_basic() {
        assert_eq!(table_to_struct_name("users"), "Users");
        assert_eq!(table_to_struct_name("order_items"), "OrderItems");
    }

    #[test]
    fn map_pg_maps_core_types() {
        let (t, _) = map_pg_to_rust("integer", "int4", false).unwrap();
        assert_eq!(t, "i32");
        let (t, _) = map_pg_to_rust("integer", "int4", true).unwrap();
        assert_eq!(t, "Option<i32>");
        assert!(map_pg_to_rust("unknown_type_xyz", "bad", false).is_none());
    }

    #[test]
    fn sanitize_field_ident_raw_keyword() {
        assert_eq!(sanitize_field_ident("type"), "r#type");
        assert_eq!(sanitize_field_ident("email"), "email");
    }
}
