//! PostgreSQL → Rust `LifeModel` / `LifeRecord` sketch generation (PRD Phase A).
//!
//! Introspects `information_schema` and emits conservative Rust types. Unknown types are
//! omitted with a comment line (SI-2).

use lifeguard::LifeExecutor;
use lifeguard::LifeError;
use may_postgres::Row;
use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

/// Options for [`infer_schema_rust`].
#[derive(Debug, Clone)]
pub struct InferOptions {
    /// PostgreSQL schema name (e.g. `public`).
    pub schema: String,
    /// If non-empty, only these tables (unqualified names, matched case-sensitively as in PG).
    pub tables: Vec<String>,
}

impl Default for InferOptions {
    fn default() -> Self {
        Self {
            schema: "public".to_string(),
            tables: Vec::new(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct ColumnMeta {
    pub table_name: String,
    pub column_name: String,
    pub ordinal: i32,
    pub data_type: String,
    pub udt_name: String,
    pub is_nullable: bool,
}

/// Introspect schema and return Rust source (module-style, stdout-friendly).
pub fn infer_schema_rust(
    executor: &dyn LifeExecutor,
    options: &InferOptions,
) -> Result<String, LifeError> {
    let columns = fetch_columns(executor, &options.schema)?;
    let pks = fetch_primary_keys(executor, &options.schema)?;
    Ok(emit_inferred_rust(options, columns, pks))
}

/// Build Rust source from introspection results (used by [`infer_schema_rust`] and golden tests).
pub(crate) fn emit_inferred_rust(
    options: &InferOptions,
    columns: Vec<ColumnMeta>,
    pks: HashMap<String, Vec<String>>,
) -> String {
    let mut by_table: HashMap<String, Vec<ColumnMeta>> = HashMap::new();
    for c in columns {
        if !options.tables.is_empty() && !options.tables.iter().any(|t| t == &c.table_name) {
            continue;
        }
        by_table
            .entry(c.table_name.clone())
            .or_default()
            .push(c);
    }

    for cols in by_table.values_mut() {
        cols.sort_by_key(|c| c.ordinal);
    }

    let mut table_names: Vec<String> = by_table.keys().cloned().collect();
    table_names.sort();

    let mut need_chrono = false;
    let mut need_uuid = false;
    let mut need_json = false;
    let mut need_decimal = false;
    for c in by_table.values().flatten() {
        if let Some((_, _)) = map_pg_to_rust(&c.data_type, &c.udt_name, c.is_nullable) {
            let dt = c.data_type.as_str();
            let udt = c.udt_name.as_str();
            if matches!(
                dt,
                "timestamp without time zone"
                    | "timestamp with time zone"
                    | "date"
            ) || matches!(udt, "timestamptz" | "timestamp")
            {
                need_chrono = true;
            }
            if dt == "uuid" || udt == "uuid" {
                need_uuid = true;
            }
            if matches!(dt, "json" | "jsonb") || matches!(udt, "json" | "jsonb") {
                need_json = true;
            }
            if matches!(dt, "numeric" | "decimal") || udt == "numeric" {
                need_decimal = true;
            }
        }
    }

    let mut out = String::new();
    writeln!(
        out,
        "// Generated by lifeguard-migrate infer-schema — review types and primary keys.\n\
         // PRD: docs/planning/PRD_SCHEMA_VALIDATORS_SESSION_AND_SCOPES.md\n"
    )
    .unwrap();
    writeln!(
        out,
        "use lifeguard_derive::{{LifeModel, LifeRecord}};"
    )
    .unwrap();
    if need_chrono {
        writeln!(
            out,
            "use chrono::{{DateTime, NaiveDate, NaiveDateTime, Utc}};"
        )
        .unwrap();
    }
    if need_uuid {
        writeln!(out, "use uuid::Uuid;").unwrap();
    }
    if need_json {
        writeln!(out, "use serde_json::Value;").unwrap();
    }
    if need_decimal {
        writeln!(out, "use rust_decimal::Decimal;").unwrap();
    }

    for table in table_names {
        let Some(mut cols) = by_table.remove(&table) else {
            continue;
        };
        let pk_cols: Vec<String> = pks.get(&table).cloned().unwrap_or_default();
        let pk_set: HashSet<String> = pk_cols.iter().cloned().collect();

        let struct_name = table_to_struct_name(&table);
        writeln!(out).unwrap();
        writeln!(out, "/// Table `{}`.`{}`", options.schema, table).unwrap();
        writeln!(
            out,
            "#[derive(Debug, Clone, PartialEq, LifeModel, LifeRecord)]"
        )
        .unwrap();
        writeln!(out, "#[table_name = \"{}\"]", table).unwrap();
        writeln!(out, "pub struct {} {{", struct_name).unwrap();

        for col in &cols {
            let rust_type = map_pg_to_rust(&col.data_type, &col.udt_name, col.is_nullable);
            if let Some((ty, attrs)) = rust_type {
                let field = sanitize_field_ident(&col.column_name);
                for line in attrs {
                    writeln!(out, "    {}", line).unwrap();
                }
                if pk_set.contains(&col.column_name) {
                    writeln!(out, "    #[primary_key]").unwrap();
                }
                writeln!(out, "    pub {}: {},", field, ty).unwrap();
            } else {
                writeln!(
                    out,
                    "    // OMITTED: {} — unsupported type data_type={} udt_name={}",
                    col.column_name, col.data_type, col.udt_name
                )
                .unwrap();
            }
        }

        writeln!(out, "}}").unwrap();
    }

    out
}

fn fetch_columns(
    executor: &dyn LifeExecutor,
    schema: &str,
) -> Result<Vec<ColumnMeta>, LifeError> {
    let sql = r"
        SELECT table_name, column_name, ordinal_position, data_type, udt_name, is_nullable
        FROM information_schema.columns
        WHERE table_schema = $1
        ORDER BY table_name, ordinal_position
    ";
    let rows = executor.query_all(sql, &[&schema])?;
    let mut out = Vec::with_capacity(rows.len());
    for row in rows {
        out.push(parse_column_row(row)?);
    }
    Ok(out)
}

fn parse_column_row(row: Row) -> Result<ColumnMeta, LifeError> {
    let table_name: String = row
        .try_get(0)
        .map_err(|e| LifeError::Other(format!("infer schema column table_name: {e}")))?;
    let column_name: String = row
        .try_get(1)
        .map_err(|e| LifeError::Other(format!("infer schema column_name: {e}")))?;
    let ordinal: i32 = row
        .try_get(2)
        .map_err(|e| LifeError::Other(format!("infer schema ordinal: {e}")))?;
    let data_type: String = row
        .try_get(3)
        .map_err(|e| LifeError::Other(format!("infer schema data_type: {e}")))?;
    let udt_name: String = row
        .try_get(4)
        .map_err(|e| LifeError::Other(format!("infer schema udt_name: {e}")))?;
    let is_nullable: String = row
        .try_get(5)
        .map_err(|e| LifeError::Other(format!("infer schema is_nullable: {e}")))?;
    let is_nullable = is_nullable.eq_ignore_ascii_case("YES");
    Ok(ColumnMeta {
        table_name,
        column_name,
        ordinal,
        data_type,
        udt_name,
        is_nullable,
    })
}

fn fetch_primary_keys(
    executor: &dyn LifeExecutor,
    schema: &str,
) -> Result<HashMap<String, Vec<String>>, LifeError> {
    let sql = r"
        SELECT tc.table_name, kcu.column_name, kcu.ordinal_position
        FROM information_schema.table_constraints AS tc
        JOIN information_schema.key_column_usage AS kcu
          ON tc.constraint_catalog = kcu.constraint_catalog
         AND tc.constraint_schema = kcu.constraint_schema
         AND tc.constraint_name = kcu.constraint_name
        WHERE tc.table_schema = $1
          AND tc.constraint_type = 'PRIMARY KEY'
        ORDER BY tc.table_name, kcu.ordinal_position
    ";
    let rows = executor.query_all(sql, &[&schema])?;
    let mut map: HashMap<String, Vec<String>> = HashMap::new();
    for row in rows {
        let table: String = row
            .try_get(0)
            .map_err(|e| LifeError::Other(format!("infer pk table_name: {e}")))?;
        let col: String = row
            .try_get(1)
            .map_err(|e| LifeError::Other(format!("infer pk column_name: {e}")))?;
        map.entry(table).or_default().push(col);
    }
    Ok(map)
}

/// Returns `(type_str, extra_attr_lines)` or `None` if unsupported.
fn map_pg_to_rust(data_type: &str, udt_name: &str, nullable: bool) -> Option<(String, Vec<String>)> {
    let base = match data_type {
        "integer" | "int4" => "i32".to_string(),
        "bigint" | "int8" => "i64".to_string(),
        "smallint" | "int2" => "i16".to_string(),
        "boolean" | "bool" => "bool".to_string(),
        "text" | "character varying" | "varchar" | "character" | "char" | "name" => "String".to_string(),
        "timestamp without time zone" => "chrono::NaiveDateTime".to_string(),
        "timestamp with time zone" => "chrono::DateTime<chrono::Utc>".to_string(),
        "date" => "chrono::NaiveDate".to_string(),
        "uuid" => "uuid::Uuid".to_string(),
        "json" | "jsonb" => "serde_json::Value".to_string(),
        "numeric" | "decimal" => "rust_decimal::Decimal".to_string(),
        "double precision" => "f64".to_string(),
        "real" | "float4" => "f32".to_string(),
        "bytea" => "Vec<u8>".to_string(),
        _ => match udt_name {
            "int4" => "i32".to_string(),
            "int8" => "i64".to_string(),
            "int2" => "i16".to_string(),
            "bool" => "bool".to_string(),
            "text" | "varchar" => "String".to_string(),
            "uuid" => "uuid::Uuid".to_string(),
            "json" | "jsonb" => "serde_json::Value".to_string(),
            "numeric" => "rust_decimal::Decimal".to_string(),
            "timestamptz" => "chrono::DateTime<chrono::Utc>".to_string(),
            "timestamp" => "chrono::NaiveDateTime".to_string(),
            _ => return None,
        },
    };

    let ty = if nullable {
        format!("Option<{base}>")
    } else {
        base
    };
    Some((ty, Vec::new()))
}

fn table_to_struct_name(table: &str) -> String {
    table
        .split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().chain(c).collect(),
            }
        })
        .collect()
}

fn sanitize_field_ident(name: &str) -> String {
    match name {
        "type" | "mod" | "fn" | "let" | "struct" | "enum" | "use" | "crate" | "self" | "super"
        | "where" | "ref" | "mut" | "move" | "async" | "await" | "loop" | "match" => {
            format!("r#{name}")
        }
        _ => name.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn golden_path(name: &str) -> String {
        format!(
            "{}/tests/golden/{name}",
            env!("CARGO_MANIFEST_DIR")
        )
    }

    #[test]
    fn golden_emit_single_table_widgets() {
        let columns = vec![
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "name".into(),
                ordinal: 2,
                data_type: "text".into(),
                udt_name: "text".into(),
                is_nullable: true,
            },
        ];
        let mut pks = HashMap::new();
        pks.insert("widgets".into(), vec!["id".into()]);
        let got = emit_inferred_rust(&InferOptions::default(), columns, pks);
        let expected = std::fs::read_to_string(golden_path("infer_widgets.expected.rs"))
            .expect("read infer_widgets golden");
        assert_eq!(got, expected);
    }

    #[test]
    fn golden_emit_omitted_unsupported_column() {
        let columns = vec![
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "meta".into(),
                ordinal: 2,
                data_type: "unknown_pg".into(),
                udt_name: "custom".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "name".into(),
                ordinal: 3,
                data_type: "text".into(),
                udt_name: "text".into(),
                is_nullable: true,
            },
        ];
        let mut pks = HashMap::new();
        pks.insert("widgets".into(), vec!["id".into()]);
        let got = emit_inferred_rust(&InferOptions::default(), columns, pks);
        let expected = std::fs::read_to_string(golden_path("infer_omitted_column.expected.rs"))
            .expect("read infer_omitted_column golden");
        assert_eq!(got, expected);
    }

    #[test]
    fn golden_emit_composite_primary_key() {
        let columns = vec![
            ColumnMeta {
                table_name: "pair_keys".into(),
                column_name: "site_id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "pair_keys".into(),
                column_name: "item_id".into(),
                ordinal: 2,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
        ];
        let mut pks = HashMap::new();
        pks.insert(
            "pair_keys".into(),
            vec!["site_id".into(), "item_id".into()],
        );
        let got = emit_inferred_rust(&InferOptions::default(), columns, pks);
        let expected = std::fs::read_to_string(golden_path("infer_composite_pk.expected.rs"))
            .expect("read infer_composite_pk golden");
        assert_eq!(got, expected);
    }

    #[test]
    fn golden_table_filter_includes_only_named_tables() {
        let columns = vec![
            ColumnMeta {
                table_name: "aaa_other".into(),
                column_name: "id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "widgets".into(),
                column_name: "name".into(),
                ordinal: 2,
                data_type: "text".into(),
                udt_name: "text".into(),
                is_nullable: true,
            },
        ];
        let mut pks = HashMap::new();
        pks.insert("aaa_other".into(), vec!["id".into()]);
        pks.insert("widgets".into(), vec!["id".into()]);
        let opts = InferOptions {
            schema: "public".into(),
            tables: vec!["widgets".into()],
        };
        let got = emit_inferred_rust(&opts, columns, pks);
        let expected = std::fs::read_to_string(golden_path("infer_widgets.expected.rs"))
            .expect("read infer_widgets golden");
        assert_eq!(got, expected);
    }

    #[test]
    fn golden_sql_keyword_column_becomes_raw_identifier() {
        let columns = vec![
            ColumnMeta {
                table_name: "kind_rows".into(),
                column_name: "id".into(),
                ordinal: 1,
                data_type: "integer".into(),
                udt_name: "int4".into(),
                is_nullable: false,
            },
            ColumnMeta {
                table_name: "kind_rows".into(),
                column_name: "type".into(),
                ordinal: 2,
                data_type: "text".into(),
                udt_name: "text".into(),
                is_nullable: false,
            },
        ];
        let mut pks = HashMap::new();
        pks.insert("kind_rows".into(), vec!["id".into()]);
        let got = emit_inferred_rust(&InferOptions::default(), columns, pks);
        let expected = std::fs::read_to_string(golden_path("infer_sql_keyword_field.expected.rs"))
            .expect("read infer_sql_keyword_field golden");
        assert_eq!(got, expected);
    }

    #[test]
    fn table_to_struct_name_basic() {
        assert_eq!(table_to_struct_name("users"), "Users");
        assert_eq!(table_to_struct_name("order_items"), "OrderItems");
    }

    #[test]
    fn map_pg_maps_core_types() {
        let (t, _) = map_pg_to_rust("integer", "int4", false).unwrap();
        assert_eq!(t, "i32");
        let (t, _) = map_pg_to_rust("integer", "int4", true).unwrap();
        assert_eq!(t, "Option<i32>");
        assert!(map_pg_to_rust("unknown_type_xyz", "bad", false).is_none());
    }

    #[test]
    fn sanitize_field_ident_raw_keyword() {
        assert_eq!(sanitize_field_ident("type"), "r#type");
        assert_eq!(sanitize_field_ident("email"), "email");
    }
}
