global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'lifeguard'
    static_configs:
      - targets: ['host.docker.internal:9898']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
