//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

#[allow(unused_imports)]
pub use super::appointments::Entity as Appointments;
#[allow(unused_imports)]
pub use super::owners::Entity as Owners;
#[allow(unused_imports)]
pub use super::pets::Entity as Pets;
