//! Query Builder Examples - Epic 02 Story 04
//!
//! Demonstrates various query patterns using the SeaQuery-based query builder.

use lifeguard::{connect, MayPostgresExecutor, LifeExecutor, SelectQuery, FromRow};
use sea_query::{Expr, Order, ExprTrait};
use may_postgres::Row;

// Example model for demonstration
// In a real application, this would be generated by the LifeModel derive macro
struct UserModel {
    id: i32,
    name: String,
    email: String,
    age: i32,
}

impl FromRow for UserModel {
    fn from_row(row: &Row) -> Result<Self, may_postgres::Error> {
        Ok(UserModel {
            id: row.get("id"),
            name: row.get("name"),
            email: row.get("email"),
            age: row.get("age"),
        })
    }
}

// Simulate the find() method that would be generated by LifeModel
impl UserModel {
    fn find() -> SelectQuery<Self> {
        SelectQuery::new("users")
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Connect to database (replace with your connection string)
    let connection_string = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgresql://postgres:postgres@localhost:5432/mydb".to_string());
    
    let client = lifeguard::connect(&connection_string)
        .map_err(|e| format!("Connection error: {}", e))?;
    let executor = MayPostgresExecutor::new(client);

    // Example 1: Basic query with filter
    println!("Example 1: Basic query with filter");
    let _users = UserModel::find()
        .filter(Expr::col("age").gte(18))
        .all(&executor)?;
    // Returns all users with age >= 18

    // Example 2: Query with ordering
    println!("Example 2: Query with ordering");
    let _users = UserModel::find()
        .filter(Expr::col("age").gte(18))
        .order_by("name", Order::Asc)
        .all(&executor)?;
    // Returns users ordered by name

    // Example 3: Query with pagination
    println!("Example 3: Query with pagination");
    let _users = UserModel::find()
        .filter(Expr::col("age").gte(18))
        .order_by("id", Order::Asc)
        .limit(10)
        .offset(20)
        .all(&executor)?;
    // Returns 10 users starting from offset 20 (page 3, 10 per page)

    // Example 4: Query with multiple filters
    println!("Example 4: Query with multiple filters");
    let _users = UserModel::find()
        .filter(Expr::col("age").gte(18))
        .filter(Expr::col("age").lte(65))
        .filter(Expr::col("email").like("%@example.com"))
        .all(&executor)?;
    // Returns users between 18-65 with example.com email

    // Example 5: Query with grouping and having
    println!("Example 5: Query with grouping and having");
    // Note: This requires custom SELECT columns for aggregation
    // For now, this demonstrates the API
    let _query = UserModel::find()
        .group_by("age")
        .having(Expr::col("COUNT(*)").gt(1));
    // Groups by age and filters groups with count > 1

    // Example 6: Complex query
    println!("Example 6: Complex query");
    let _users = UserModel::find()
        .filter(Expr::col("age").gte(18))
        .filter(Expr::col("name").like("John%"))
        .order_by("age", Order::Desc)
        .order_by("name", Order::Asc)
        .limit(5)
        .all(&executor)?;
    // Returns top 5 users named "John*" ordered by age (desc) then name (asc)

    // Example 7: Single result query
    println!("Example 7: Single result query");
    let _user = UserModel::find()
        .filter(Expr::col("id").eq(1))
        .one(&executor)?;
    // Returns a single user with id = 1, or error if not found

    // Example 8: Query with custom expressions
    println!("Example 8: Query with custom expressions");
    let _users = UserModel::find()
        .filter(Expr::col("age").add(Expr::val(1)).gt(20))
        .all(&executor)?;
    // Returns users where age + 1 > 20 (i.e., age > 19)

    println!("All query examples completed successfully!");
    Ok(())
}

// Note: This example requires a database connection to run.
// To test the query building (without execution), you can use the unit tests in src/query.rs
