// Generated by lifeguard-migrate infer-schema — review types and primary keys.
// PRD: docs/planning/PRD_SCHEMA_VALIDATORS_SESSION_AND_SCOPES.md

use lifeguard_derive::{LifeModel, LifeRecord};

/// Table `public`.`kind_rows`
#[derive(Debug, Clone, PartialEq, LifeModel, LifeRecord)]
#[table_name = "kind_rows"]
pub struct KindRows {
    #[primary_key]
    pub id: i32,
    pub r#type: String,
}
