// Generated by lifeguard-migrate infer-schema — review types and primary keys.
// PRD: docs/planning/PRD_SCHEMA_VALIDATORS_SESSION_AND_SCOPES.md

use lifeguard_derive::{LifeModel, LifeRecord};

/// Table `public`.`widgets`
#[derive(Debug, Clone, PartialEq, LifeModel, LifeRecord)]
#[table_name = "widgets"]
pub struct Widgets {
    #[primary_key]
    pub id: i32,
    // OMITTED: meta — unsupported type data_type=unknown_pg udt_name=custom
    pub name: Option<String>,
}
