// Generated by lifeguard-migrate infer-schema — review types and primary keys.
// PRD: docs/planning/PRD_SCHEMA_VALIDATORS_SESSION_AND_SCOPES.md

use lifeguard_derive::{LifeModel, LifeRecord};

/// Table `public`.`pair_keys`
#[derive(Debug, Clone, PartialEq, LifeModel, LifeRecord)]
#[table_name = "pair_keys"]
pub struct PairKeys {
    // TODO: composite PRIMARY KEY (site_id, item_id) — confirm Lifeguard PK tuple layout.
    pub site_id: i32,
    pub item_id: i32,
}
