apiVersion: v1
kind: Service
metadata:
  name: postgresql-replica-1
  namespace: lifeguard-test
  labels:
    app: postgresql-replica-1
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app: postgresql-replica-1
