apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-primary-data
  namespace: lifeguard-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
