//! Derive macro for LifeModelTrait
//!
//! Generates LifeModelTrait implementation for Entity.
//! This is separate from LifeModel to avoid trait bound resolution issues.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{parse_macro_input, DeriveInput};

/// Generate LifeModelTrait implementation for Entity
///
/// This derive expects:
/// - Entity: unit struct (generated by DeriveEntity)
/// - Model: struct (generated by DeriveModel)
///
/// It generates: `impl LifeModelTrait for Entity { type Model = Model; }`
pub fn derive_life_model_trait(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    
    let entity_name = &input.ident;
    
    // Extract Model name from attributes or infer from Entity name
    // In SeaORM, Model is typically named "Model" in the same module
    // For now, we'll require users to specify the Model type via attribute
    // TODO: Infer Model name from context
    
    // For now, assume Model is in the same scope and named "{Entity}Model"
    // This is a simplification - in practice, users might need to specify it
    let model_name = syn::Ident::new(
        &format!("{}Model", entity_name),
        entity_name.span()
    );
    
    let expanded: TokenStream2 = quote! {
        // Implement LifeModelTrait for Entity
        // This is separate from Model generation to avoid trait bound resolution issues
        impl lifeguard::LifeModelTrait for #entity_name {
            type Model = #model_name;
        }
    };
    
    TokenStream::from(expanded)
}
