//! Derive macro for Model
//!
//! Generates Model struct and ModelTrait implementation.
//! Note: FromRow is a separate derive macro.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{parse_macro_input, Data, DeriveInput, Fields};

// Model derive doesn't need utils - it just generates the struct

/// Generate Model struct and ModelTrait implementation
pub fn derive_model(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    
    let struct_name = &input.ident;
    
    // Extract struct fields
    let fields = match &input.data {
        Data::Struct(syn::DataStruct {
            fields: Fields::Named(fields),
            ..
        }) => &fields.named,
        _ => {
            return syn::Error::new_spanned(
                &input.ident,
                "DeriveModel can only be derived for structs with named fields",
            )
            .to_compile_error()
            .into();
        }
    };
    
    // Generate model fields
    let model_fields: Vec<TokenStream2> = fields
        .iter()
        .map(|field| {
            let field_name = field.ident.as_ref().unwrap();
            let field_type = &field.ty;
            quote! {
                pub #field_name: #field_type,
            }
        })
        .collect();
    
    let expanded: TokenStream2 = quote! {
        // Model struct (immutable row representation)
        #[derive(Debug, Clone)]
        pub struct #struct_name {
            #(#model_fields)*
        }
        
        // NOTE: FromRow implementation is generated by a separate derive macro
        // Users should apply #[derive(FromRow)] to the Model struct separately.
    };
    
    TokenStream::from(expanded)
}
